### ISSUE TITLE
这事咋回事呢

### ISSUE THREAD

**Issue by jinyuan1299188702** [Alivon/Panda-Learning#101]
开启： 获取更新信息...
正在联网获取跟新信息...
输入用户标记名：熊猫学习唯一下载地址为 https://github.com/Alivon/Panda-Learning
程序版本为：v3.0 preview，
最新版本为： v2.0 preview 主要更新说明：当前版本位preview预览版，不能保证程序鲁棒性，若发现程序逻辑问题以及有更好的建议 请在项目github上提交issues。
更新显示不会打断之前操作，请继续...

输入之后~~~~

Exception in thread 文章学习:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "pdlearn\threads.py", line 23, in run
  File "pandalearning.py", line 60, in article
  File "pdlearn\mydriver.py", line 85, in set_cookies
  File "pdlearn\mydriver.py", line 85, in <dictcomp>
KeyError: 'expiry'

**Comment by liyuan97** [comment]
我也遇到了

**Comment by daeryou1** [comment]
+1

**Comment by liuhaiyangliuhaiyang** [comment]
一样的问题，是不是升级了？

**Comment by liuhaiyangliuhaiyang** [comment]
1.8版也是这个问题。
