### ISSUE TITLE
Exception in thread 视频学习: Traceback (most recent call last):   File "threading.py", line 916, in _bootstrap_inner   File "pdlearn\threads.py", line 23, in run   File "pandalearning.py", line 118, in video   File "pdlearn\mydriver.py", line 85, in set_cookies   File "pdlearn\mydriver.py", line 85, in <dictcomp> KeyError: 'expiry'  Exception in thread 文章学习: Traceback (most recent call last):   File "threading.py", line 916, in _bootstrap_inner   File "pdlearn\threads.py", line 23, in run   File "pandalearning.py", line 60, in article   File "pdlearn\mydriver.py", line 85, in set_cookies   File "pdlearn\mydriver.py", line 85, in <dictcomp> KeyError: 'expiry'

### ISSUE THREAD

**Issue by massger** [Alivon/Panda-Learning#102]

**Comment by daeryou1** [comment]
类似问题，麻烦解决下？

**Comment by gzip2009** [comment]
昨天还正常，今天早上遇到和楼主同样的问题。我先把目录中的USER文件夹删除，再进入，还是没有解决。

**Comment by gzip2009** [comment]
今天，这APP取消了学习排名

**Comment by Alivon** [comment]
已修复解决
