### ISSUE TITLE
昨晚到12点过就不行了

### ISSUE THREAD

**Issue by bifu123** [Alivon/Panda-Learning#106]
开始还行，很顺利，昨晚到12点过就不行了，是不是对方网页有了改动还是什么的？
`DevTools listening on ws://127.0.0.1:62171/devtools/browser/2e2c2882-beac-45ed-b17e-308883993bc1
Exception in thread 文章学习:
Traceback (most recent call last):
  File "d:\python\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\python\workspace\panda-learn\pdlearn\threads.py", line 23, in run
    self.func(*self.args)
  File ".\pandalearning.py", line 60, in article
    driver_article.set_cookies(cookies)
  File "D:\python\workspace\panda-learn\pdlearn\mydriver.py", line 87, in set_cookies
    self.driver.add_cookie({k: cookie[k] for k in {'name', 'value', 'domain', 'path', 'expiry'}})
  File "D:\python\workspace\panda-learn\pdlearn\mydriver.py", line 87, in <dictcomp>
    self.driver.add_cookie({k: cookie[k] for k in {'name', 'value', 'domain', 'path', 'expiry'}})
KeyError: 'expiry'

Exception in thread 视频学习:
Traceback (most recent call last):
  File "d:\python\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\python\workspace\panda-learn\pdlearn\threads.py", line 23, in run
    self.func(*self.args)
  File ".\pandalearning.py", line 118, in video
    driver_video.set_cookies(cookies)
  File "D:\python\workspace\panda-learn\pdlearn\mydriver.py", line 87, in set_cookies
    self.driver.add_cookie({k: cookie[k] for k in {'name', 'value', 'domain', 'path', 'expiry'}})
  File "D:\python\workspace\panda-learn\pdlearn\mydriver.py", line 87, in <dictcomp>
    self.driver.add_cookie({k: cookie[k] for k in {'name', 'value', 'domain', 'path', 'expiry'}})
KeyError: 'expiry'

总计用时0.6166666666666667分钟`

**Comment by xiuluo211314** [comment]
积分规则已变更

**Comment by Smartquan** [comment]
软件更新了

**Comment by bifu123** [comment]
把源码也更新一下

**Comment by shen159876** [comment]
把源码和软件更新一下试试
