### ISSUE TITLE
貌似被盯上了吧

### ISSUE THREAD

**Issue by shenzheke** [Alivon/Panda-Learning#107]
File "pandalearn.py", line 101, in check
  File "lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearn.py", line 256, in <module>
  File "pandalearn.py", line 107, in check
  File "pandalearn.py", line 66, in login
  File "pandalearn.py", line 91, in check
  File "pandalearn.py", line 91, in <dictcomp>
KeyError: 'expiry'
[13104] Failed to execute script pandalearn

**Comment by 79980730** [comment]
是积分政策调整的原因吧。

**Comment by Smartquan** [comment]
app更新了而已

**Comment by bifu123** [comment]
反正不行了

**Comment by bifu123** [comment]
老大在哪里？粉丝群众在水深火热中，需要你的出现

**Comment by bifu123** [comment]
DevTools listening on ws://127.0.0.1:62379/devtools/browser/e8de3e4d-a994-470f-8d28-e7cb386a75d6
文章学习中，文章总时长剩余480秒当前学习总积分：91
阅读文章:6/6,观看视频:5/6,登陆:1/1,文章时长:6/8,视频时长:6/10
文章学习中，文章总时长剩余455秒

又可以了

**Comment by cxl008** [comment]
少了个键值而已啊

**Comment by guxd** [comment]
for cookie in cookies:  # 添加cookies
        driver_video.add_cookie(cookie)

**Comment by Going2333** [comment]
不是被盯上了，今天强国改版更新了。

**Comment by shenzheke** [comment]
没仔细看说明，不好意思
