### ISSUE TITLE
mac用不了

### ISSUE THREAD

**Issue by wangwangyh** [Alivon/Panda-Learning#150]
Traceback (most recent call last):
  File "selenium/webdriver/common/service.py", line 76, in start
  File "subprocess.py", line 729, in __init__
  File "subprocess.py", line 1364, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: './chromedriver': './chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearning.py", line 176, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn/dingding.py", line 23, in dd_login_status
  File "pdlearn/mydriver.py", line 22, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 73, in __init__
  File "selenium/webdriver/common/service.py", line 83, in start
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

[6010] Failed to execute script pandalearning
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

这个是什么意思

**Comment by Alivon** [comment]
mac需要终端用命令打开，不然path路径会错误

**Comment by wangwangyh** [comment]
> mac需要终端用命令打开，不然path路径会错误

请问如何使用终端打开，小白不懂，还请大佬明示。我已经是打开方式选择终端了

**Comment by Alivon** [comment]
命令行启动程序 输入 ./pandalearning

**Comment by wangwangyh** [comment]
> 命令行启动程序 输入 ./pandalearning

... 具体是怎么操作呢。还是不懂
