### ISSUE TITLE
win10x64,2.3preview 运行一段时间出现tls证书错误

### ISSUE THREAD

**Issue by lxmoso21** [Alivon/Panda-Learning#153]
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "pdlearn\threads.py", line 23, in run
  File "pandalearning.py", line 73, in article
  File "pandalearning.py", line 49, in show_score
  File "pdlearn\score.py", line 10, in get_score
  File "lib\site-packages\requests\api.py", line 75, in get
  File "lib\site-packages\requests\api.py", line 60, in request
  File "lib\site-packages\requests\sessions.py", line 533, in request
  File "lib\site-packages\requests\sessions.py", line 646, in send
  File "lib\site-packages\requests\adapters.py", line 416, in send
  File "lib\site-packages\requests\adapters.py", line 228, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: Z:\TEMP\_MEI32642\certifi\cacert.pem
版本：2.3 preview，显示上述信息后，自动推出，但实际上学习还没有完成。

**Comment by Alivon** [comment]
其他win64没有出现过该问题，正常应该不会出现，打包是包含了证书的，第二次运行还是这样吗。

**Comment by lxmoso21** [comment]
第二次运行还是这样，不过我的机器使用ramdisk ，chrome的临时目录放进了ramdisk，每次关机都会清空，是不是这个原因导致证书缺失？

**Comment by lxmoso21** [comment]
> 其他win64没有出现过该问题，正常应该不会出现，打包是包含了证书的，第二次运行还是这样吗。

我看了一下，某些情况下，临时目录缺了很多文件。请问如何排查一下?
