### ISSUE TITLE
mac 今天开始报错了

### ISSUE THREAD

**Issue by muchao** [Alivon/Panda-Learning#155]
昨天可以正常 今天来了 运行命令提示如下报错信息
========================================================================================================================
更新显示不会打断之前输入操作，请继续...

读取用户信息成功
Traceback (most recent call last):
  File "pandalearning.py", line 176, in <module>
  File "pandalearning.py", line 15, in user_flag
  File "pdlearn/dingding.py", line 23, in dd_login_status
  File "pdlearn/mydriver.py", line 22, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 73, in __init__
  File "selenium/webdriver/common/service.py", line 104, in start
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service ./chromedriver

[3468] Failed to execute script pandalearning

**Comment by Alivon** [comment]
命令行运行  这个是没找到目录下Chromedriver 检查路径

**Comment by muchao** [comment]
> 命令行运行 这个是没找到目录下Chromedriver 检查路径

就是命令行运行的 终端 cd 进到目录 然后 ./pandalearning 执行 报错如主题贴
chromedriver 在pandalearning同目录

**Comment by muchao** [comment]
找到问题了，是我的一个软件把host文件改了 host文件里面少了127.0.0.1 localhost这一行 导致selenium无法加载web驱动 这是python版selenium的一个小bug  正确修改完host 程序已经可正常运行了！
