### ISSUE TITLE
centos7 报错

### ISSUE THREAD

**Issue by ljkk** [Alivon/Panda-Learning#157]
```
开启： 获取更新信息...

正在联网获取跟新信息...
输入用户标记名：熊猫学习唯一下载地址为 https://github.com/Alivon/Panda-Learning
程序版本为：v2.3 preview，
最新版本为：v2.3 preview
========================================================================================================================
========================================================================================================================
更新提要：
当前版本为preview预览版，请积极在项目github上提交issues。
重要更新，因为强国修改积分规则请至github请重新下载2.1以上版本，否则无法使用。
网页积分学习上线为25分，望周知。
========================================================================================================================
更新显示不会打断之前输入操作，请继续...

是否保存钉钉帐户密码，保存后可后免登陆学习(Y/N) y
请输入正确的学习强国帐号(钉钉手机号)：***********
请输入学习强国密码：**********
Traceback (most recent call last):
  File "pandalearning.py", line 176, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn/dingding.py", line 23, in dd_login_status
  File "pdlearn/mydriver.py", line 22, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 81, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 157, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 252, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 3.10.0-693.2.2.el7.x86_64 x86_64)

[6986] Failed to execute script pandalearning
[root@4710419222 xxqg]# 
```
所有程序都是从主页下载的, 解压压缩包, 运行pandalearning 报错, 
首先排除路径问题, 应该也不是chrome和chromedriver的版本问题

**Comment by herocspx** [comment]
windows版也报Failed to execute script pandalearning

**Comment by zyftank** [comment]
楼主试一下给chrome加个参数
–disable-dev-shm-usage

**Comment by ljkk** [comment]
> 楼主试一下给chrome加个参数
> –disable-dev-shm-usage

加在哪里, 我百度的资料是加在 /usr/bin/google-chrome 文件的最后一行, 还是不好使

**Comment by ljkk** [comment]
解决了, 直接运行源码就可以了
