### ISSUE TITLE
V2.4 发布，增强防检测功能，源码适配各种平台

### ISSUE THREAD

**Issue by Alivon** [Alivon/Panda-Learning#172]
- Security`  增加随机请求头
- `Security`  增加文章视频学习随机滑动窗口
- `Added`  源码适配各个系统

建议使用默认多线程及后台功能，获取更好体验

**Comment by wqh966** [comment]
“无自动关机任务，已程序释放内存，00分钟后窗口将自动关闭。”
小问题，应该是“程序已释放内存”吧，“00分钟后.....”应该是楼主忘记写时间了：）

**Comment by Alivon** [comment]
> “无自动关机任务，已程序释放内存，00分钟后窗口将自动关闭。”
> 小问题，应该是“程序已释放内存”吧，“00分钟后.....”应该是楼主忘记写时间了：）

哈哈哈是 10分钟写出00分钟了。。
就是没有开启自动关机任务的会在10分钟后关闭程序窗口

**Comment by wqh966** [comment]
不加参数应该就是默认多线程及后台学习吧？

**Comment by MQL9011** [comment]
请问 VPS  Ubuntu请大佬们给个部署指南。

**Comment by xenonum** [comment]
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn/dingding.py", line 23, in dd_login_status
  File "pdlearn/mydriver.py", line 38, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 81, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 157, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 252, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.15.0-47-generic x86_64)

[32293] Failed to execute script pandalearning
system: ubuntu 18.04
how to fix it?

**Comment by liangxyz** [comment]
感谢大佬的辛勤劳动，想提一个建议，文章和视频学习时间能不能也随机话一下？否则都是固定的2分钟或者3分钟，很有可能被认为是机器人啊

**Comment by mazda1152** [comment]
单线程和多线程各有什么优点？
虽然现很安全
单线程是不是更不容易被检测

**Comment by Alivon** [comment]
> ChromeDriver is assuming that Chrome has crashed.)

检查 chrome和是否和chromedriver对应

**Comment by Alivon** [comment]
> 感谢大佬的辛勤劳动，想提一个建议，文章和视频学习时间能不能也随机话一下？否则都是固定的2分钟或者3分钟，很有可能被认为是机器人啊

放心使用

**Comment by Alivon** [comment]
> 单线程和多线程各有什么优点？
> 虽然现很安全
> 单线程是不是更不容易被检测
因为人们手动刷分也是开两个以上窗口
so 放心使用

**Comment by zzs3579** [comment]
我下了windows完整版打开看着还是2.3版啊

**Comment by HaishuoFang** [comment]
您好，Alivon，现在刷分最高到25是吧？应该没看错把

**Comment by Alivon** [comment]
> 您好，Alivon，现在刷分最高到25是吧？应该没看错把

是的
