### ISSUE TITLE
用树莓派，出现了以下错误。

### ISSUE THREAD

**Issue by Linjianxuan** [Alivon/Panda-Learning#185]
File "./pandalearning.py", line 17
SyntaxError: Non-ASCII character '\xe6' in file ./pandalearning.py on line 17, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
root@raspberrypi:/home/pi/Downloads/Panda-Learning-master/Source Packages# python3 ./pandalearning.py 
Traceback (most recent call last):
  File "./pandalearning.py", line 6, in <module>
    from pdlearn import dingding
  File "/home/pi/Downloads/Panda-Learning-master/Source Packages/pdlearn/dingding.py", line 2, in <module>
    from pdlearn import mydriver
  File "/home/pi/Downloads/Panda-Learning-master/Source Packages/pdlearn/mydriver.py", line 1, in <module>
    from selenium import webdriver
ImportError: No module named 'selenium'

**Comment by AthenaCN** [comment]
selenium组件没装
# pip3 install selenium

**Comment by Alivon** [comment]
树莓派问题 查看[issue143](https://github.com/Alivon/Panda-Learning/issues/143)
