### ISSUE TITLE
在UbuntuServer18.04下把Chrome和ChromeDriver装好了，但是执行报错

### ISSUE THREAD

**Issue by EdwardZhu91** [Alivon/Panda-Learning#191]
Chrome --version：Google Chrome 73.0.3683.75 unknown；
ChromeDriver --version：ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72)；
报错信息：
`开启： 获取更新信息...
输入用户标记名：
正在联网获取更新信息...
熊猫学习唯一下载地址为 https://github.com/Alivon/Panda-Learning
程序版本为：v2.4，
最新版本为：v2.4
========================================================================================================================
========================================================================================================================
更新提要：
当前最新版本为2.4稳定版，请积极在项目github上提交issues。
- Security`  增加随机请求头
- `Security`  增加文章视频学习随机滑动窗口
- `Added`  源码适配各个系统
防检测加强，建议默认后台学习及开启多线程
========================================================================================================================
更新显示不会打断之前输入操作，请继续...

是否保存钉钉帐户密码，保存后可后免登陆学习(Y/N) N
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "pandalearning.py", line 18, in user_flag
    driver_login = mydriver.Mydriver(nohead=False)
  File "/root/Panda-Learning/Source Packages/pdlearn/mydriver.py", line 46, in __init__
    self.driver = self.webdriver.Chrome(chrome_options=self.options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.15.0-47-generic x86_64)
`
用编译好的文件或者源文件都是这个报错。

**Comment by Alivon** [comment]
应该是chrome更新了  driver还是72版本

**Comment by bdya2005** [comment]
用普通用户运行试试,另外，为chromdriver +777。

**Comment by bobotoy** [comment]
我也遇到这个问题，不知道怎么解决

**Comment by Rail-gun** [comment]
遇到这个问题 +1 重装了好多次chrome 和 chromdriver

**Comment by Rail-gun** [comment]
> 应该是chrome更新了 driver还是72版本

chrome 和chromdriver重装了好几次对应版本还是不行

**Comment by mr-zl** [comment]
树莓派也遇到同样的问题，不知道问题出在哪里

**Comment by mr-zl** [comment]
应该是chrome 和chromdriver版本的问题，我的树莓派一开始也是这个问题，后来我重装了chromium-browser-l10n_72.0.3626.121-0+rpt4_all.deb和chromium-chromedriver_72.0.3626.121-0+rpt4_armhf.deb就可以正常运行了。
