### ISSUE TITLE
难道就没有一个吊大的能够总结下vps安装方法？

### ISSUE THREAD

**Issue by failsray** [Alivon/Panda-Learning#194]
不管是debian还是ubantu，我想总应该有傻瓜教程的。体谅下我们这些小白，还是希望有大神能够出个教程，被这分数折磨得。替同样遇到问题的党员同志先谢谢了~

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by bdya2005** [comment]
新手小白，凭记忆写一下,.不知道对不对呀。
1.安装Linux-安装谷歌浏览器见：[https://www.cnblogs.com/don9/p/7289830.html]
（我也不清楚为什么要安装这个，但不安装运行pandalearning会报错。“”Message: Service ./chromedriver unexpectedly exited.“”）
2.root用户登录创建新用户"xxqg"
#useradd xxqg
#passwd_ xxqg
3.创建目录及授权
#mkdir /home/xxqg
#chmod +777 /home/xxqg
4.下载程序、解压及安装
#cd /home/xxqg
#wget https://github.com/Alivon/Panda-Learning/raw/linux/pandalearning-linux/pandalearning_linux.tar.gz
#tar -zxvf pandalearning_linux.tar.gz
#wget https://github.com/Alivon/Panda-Learning/raw/linux/pandalearning-linux/google-chrome-stable_current_amd64.deb
#dpkg -i google-chrome-stable_current_amd64.deb
5.用新用户xxqg登录，执行一次，标记用户名，会在/home/xxqgg下产生一个user目录。
$cd /home/xxqg
$./pandalearning
#chmod +777 /home/xxqg/user  
6.编辑脚本（用户标记名替换成自己的设置）
$vi pd.sh
cd /home/xxqg/
date >my.log
sleep $(shuf -i 1-120 -n 1)
nohup ./pandalearning 用户标记名 >>my.log 2>&1 &  
7.同步时间，选择china.beijing，.添加crontab,中午12点后自动运行。
#tzselect
#TZ='Asia/Shanghai'; export TZ
#crontab -u xxqg -e
0 12 * * * /home/xxqg/pd.sh >> /tmp/test.txt

**Comment by ZhaoqiangCn** [comment]
可以参考这个：https://book.spacesh.com/di-san-zhang-pandalearning 每个步骤应该很详细了

**Comment by failsray** [comment]
多谢两位😀

**Comment by yegeziz** [comment]
按照上面的配置好了,执行后出错
root@ubuntu1:/home# ./pandalearning
Exception in thread \u83b7\u53d6\u66f4\u65b0\u4fe1\u606f...:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "pdlearn/threads.py", line 17, in run
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

Traceback (most recent call last):
  File "pandalearning.py", line 179, in <module>
  File "pdlearn/user.py", line 10, in get_user
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
[7338] Failed to execute script pandalearning

**Comment by ZhaoqiangCn** [comment]
> 按照上面的配置好了,执行后出错
> root@ubuntu1:/home# ./pandalearning
> Exception in thread \u83b7\u53d6\u66f4\u65b0\u4fe1\u606f...:
> Traceback (most recent call last):
> File "threading.py", line 914, in _bootstrap_inner
> File "pdlearn/threads.py", line 17, in run
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
> 
> Traceback (most recent call last):
> File "pandalearning.py", line 179, in 
> File "pdlearn/user.py", line 10, in get_user
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
> [7338] Failed to execute script pandalearning

编码问题，前面加上这个 PYTHONIOENCODING=utf-8 python3 ×××××××

**Comment by yunzcm** [comment]
有一键安装包就完美了，我纯小白只好在腾讯云安装了win 系统
