### ISSUE TITLE
大佬，有些环境编码有问题

### ISSUE THREAD

**Issue by ZhaoqiangCn** [Alivon/Panda-Learning#197]
```python
Traceback (most recent call last):
  File "pandalearning.py", line 179, in <module>
    dd_status, uname = user.get_user()
  File "/root/Panda-Learning-2.4/Source Packages/pdlearn/user.py", line 10, in g                                                                                                                                          et_user
Exception in thread \u83b7\u53d6\u66f4\u65b0\u4fe1\u606f...:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/root/Panda-Learning-2.4/Source Packages/pdlearn/threads.py", line 17, i                                                                                                                                          n run
    print("\u5f00\u542f\uff1a " + self.name)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordin                                                                                                                                          al not in range(128)

    uname = input("\u8f93\u5165\u7528\u6237\u6807\u8bb0\u540d\uff1a")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordin                                                                                                                                          al not in range(128)
```

**Comment by ZhaoqiangCn** [comment]
我在GCP的Debian环境 没有问题，但是在自己的Ubuntu下报这个错。

**Comment by ZhaoqiangCn** [comment]
PYTHONIOENCODING=utf-8 执行程序前加上这个已解决
