### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by fuckthegit** [Alivon/Panda-Learning#205]
macos, 2.4版本, 运行 python3 pandalearning.py 报错:
Traceback (most recent call last):
  File "pandalearning.py", line 4, in <module>
    from pdlearn import version
  File "/Users/weibin/Downloads/Panda-Learning/pdlearn/version.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
![Jietu20190411-180440](https://user-images.githubusercontent.com/43519709/55949029-4daafa00-5c84-11e9-9bc6-4be9f4d1f4b6.jpg)

**Comment by fuckthegit** [comment]
nothing
