### ISSUE TITLE
2.4 show_score(cookies)出错频繁

### ISSUE THREAD

**Issue by bifu123** [Alivon/Panda-Learning#206]
登陆中...
Traceback (most recent call last):
  File "pandalearning.py", line 181, in <module>
    total, each = show_score(cookies)
  File "pandalearning.py", line 49, in show_score
    total, each = score.get_score(cookies)
  File "C:\Users\Administrator\Desktop\Panda-Learning-master\Source Packages\pdlearn\score.py", line 14, in get_score
    each = [int(i["currentScore"]) for i in each if i["ruleId"] in [1, 2, 9, 1002, 1003]]
  File "C:\Users\Administrator\Desktop\Panda-Learning-master\Source Packages\pdlearn\score.py", line 14, in <listcomp>
    each = [int(i["currentScore"]) for i in each if i["ruleId"] in [1, 2, 9, 1002, 1003]]
TypeError: string indices must be integers

**Comment by bifu123** [comment]
脚本目录不要有空格，有则出错

**Comment by Alivon** [comment]
已修复
