### ISSUE TITLE
 登陆异常

### ISSUE THREAD

**Issue by pacocai** [Alivon/Panda-Learning#220]
DevTools listening on ws://127.0.0.1:17236/devtools/browser/edfc28d9-236c-4237-8
f5b-a942815b03c9
[0411/232609.992:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason:
Missing track ID in msid attribute.
[0411/232609.993:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason:
Missing track ID in msid attribute.
[0411/232609.993:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason:
Missing track ID in msid attribute.
[0411/232609.994:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason:
Missing track ID in msid attribute.
[0411/232609.994:ERROR:rtc_peer_connection_handler.cc(2225)] Failed to create na
tive session description. Type: offer SDP: v=0
o=- 7636593082583011147 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS
m=application 9 UDP/TLS/RTP/SAVPF 119
c=IN IP4 0.0.0.0
b=AS:30
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:dZa/
a=ice-pwd:qfTf/hjemZkV9z5HdrAvZUe7
a=ice-options:trickle
a=fingerprint:sha-256 86:56:3C:8A:FF:F4:47:A3:04:26:61:D2:44:FD:7E:33:C3:65:AC:F
3:25:A0:0B:2D:C4:4D:60:0E:AF:EA:1B:03
a=setup:actpass
a=mid:0
a=sendrecv
a=msid:
a=rtcp-mux
a=rtpmap:119 google-data/90000
a=ssrc:983506731 cname:3tojI27Mlukgnxmf
a=ssrc:983506731 msid:-
a=ssrc:983506731 mslabel:-
a=ssrc:983506731 label:

[0411/232609.995:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse Ses
sionDescription. a=msid:  Missing track ID in msid attribute.
Traceback (most recent call last):
  File "pandalearning.py", line 177, in <module>
  File "pandalearning.py", line 49, in show_score
  File "pdlearn\score.py", line 11, in get_score
TypeError: 'NoneType' object is not subscriptable
[6536] Failed to execute script pandalearning

Z:\Panda_learning-32>

**Comment by Alivon** [comment]
已修复

**Comment by liyutg** [comment]
怎麽解決的
