### ISSUE TITLE
无法登陆，显示错误

### ISSUE THREAD

**Issue by squirrelmedia** [Alivon/Panda-Learning#221]
`DevTools listening on ws://127.0.0.1:51605/devtools/browser/4c4e4583-f9f3-40ec-b9af-9ac5f361bbb9
[0412/000853.239:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0412/000853.239:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0412/000853.239:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0412/000853.239:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0412/000853.239:ERROR:rtc_peer_connection_handler.cc(2225)] Failed to create native session description. Type: offer SDP: v=0
o=- 6144476090311728233 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS
m=application 9 UDP/TLS/RTP/SAVPF 119
c=IN IP4 0.0.0.0
b=AS:30
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:qvmC
a=ice-pwd:SFDTV7BBClnoZLl/GVHS39zZ
a=ice-options:trickle
a=fingerprint:sha-256 E1:62:F1:1A:38:16:5B:27:DB:6C:05:ED:F4:47:FF:DD:1B:58:4E:64:E6:37:82:2E:A2:FF:43:14:05:08:14:A4
a=setup:actpass
a=mid:0
a=sendrecv
a=msid:
a=rtcp-mux
a=rtpmap:119 google-data/90000
a=ssrc:1499974677 cname:VXpDMrPuEPWbqD1W
a=ssrc:1499974677 msid:-
a=ssrc:1499974677 mslabel:-
a=ssrc:1499974677 label:

[0412/000853.239:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.
登陆中...
Traceback (most recent call last):
  File "pandalearning.py", line 181, in <module>
  File "pandalearning.py", line 49, in show_score
  File "pdlearn\score.py", line 14, in get_score
  File "pdlearn\score.py", line 14, in <listcomp>
TypeError: string indices must be integers
[2512] Failed to execute script pandalearning`

**Comment by herocspx** [comment]
软件失效了，等待作者更新吧

**Comment by bifu123** [comment]
获取积分那句失效了

**Comment by sunline1111** [comment]
不能用了，等更新吧

**Comment by Alivon** [comment]
已修复

**Comment by liyutg** [comment]
咋么修复的呢
