### ISSUE TITLE
强国网站更新，请大家等待更新修复

### ISSUE THREAD

**Issue by Alivon** [Alivon/Panda-Learning#223]
# 看到反馈，应该是强国积分获取更新，请耐心等待修复

**Comment by wdmb123** [comment]
修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决

**Comment by poemsiu** [comment]
> 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决

怎么修改？貌似没这个文件啊

**Comment by suqianstone** [comment]
> 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决

windows版本是不是要等Alivon修复？

**Comment by Alivon** [comment]
> 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决

可以PR一波代码  一行代码也是贡献

**Comment by herocspx** [comment]
> 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决
牛~~~~等作者更新

**Comment by icman02200459** [comment]
我直接用源码跑报错Traceback (most recent call last):
  File "F:\pandalearning.py", line 4, in <module>
    from pdlearn import version
  File "F:\pdlearn\version.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
谁知道怎么回事？？

**Comment by suqianstone** [comment]
![image](https://user-images.githubusercontent.com/36249530/56005435-dff1e300-5d02-11e9-8bef-aef99b2a2e11.png)

**Comment by fuckthegit** [comment]
> 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决

感谢，已经好了，能用了

**Comment by asdqwe111** [comment]
> > 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决
> 
> windows版本是不是要等Alivon修复？

层主威武，我改完以后可以了，哈哈哈哈哈

**Comment by suqianstone** [comment]
> > > 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决
> > 
> > 
> > windows版本是不是要等Alivon修复？
> 
> 层主威武，我改完以后可以了，哈哈哈哈哈

请问您什么环境修改后就好了的？

**Comment by asdqwe111** [comment]
> > > > 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决
> > > 
> > > 
> > > windows版本是不是要等Alivon修复？
> > 
> > 
> > 层主威武，我改完以后可以了，哈哈哈哈哈
> 
> 请问您什么环境修改后就好了的？

python3.6

**Comment by HarryDean2010** [comment]
> 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决

我下的EXE文件直接执行那种，文件夹里没有score.py这个文件，该怎么改？

**Comment by asdqwe111** [comment]
> > 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决
> 
> 我下的EXE文件直接执行那种，文件夹里没有score.py这个文件，该怎么改？

那就等楼主更新吧

**Comment by Alivon** [comment]
> > > > 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决
> > > 
> > > 
> > > windows版本是不是要等Alivon修复？
> > 
> > 
> > 层主威武，我改完以后可以了，哈哈哈哈哈
> 
> 请问您什么环境修改后就好了的？

你的python环境缺少依赖库，   等我晚上更新吧

**Comment by suqianstone** [comment]
> 我直接用源码跑报错Traceback (most recent call last):
> File "F:\pandalearning.py", line 4, in 
> from pdlearn import version
> File "F:\pdlearn\version.py", line 1, in 
> import requests
> ModuleNotFoundError: No module named 'requests'
> 谁知道怎么回事？？

pip install requests 安装 requests
pip install selenium 安装 selenium 
再试试

**Comment by princelai** [comment]
> 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决

牛，果然可以了哈哈

**Comment by dynamohuang** [comment]
修复PR 来了 求合并
https://github.com/Alivon/Panda-Learning/pull/228

**Comment by caotuanyuan** [comment]
已更新

**Comment by Going2333** [comment]
> > 我直接用源码跑报错Traceback (most recent call last):
> > File "F:\pandalearning.py", line 4, in
> > from pdlearn import version
> > File "F:\pdlearn\version.py", line 1, in
> > import requests
> > ModuleNotFoundError: No module named 'requests'
> > 谁知道怎么回事？？
> 
> pip install requests 安装 requests
> pip install selenium 安装 selenium
> 再试试

学习了...
自己打包exe成功，技能get

**Comment by suqianstone** [comment]
> > > 我直接用源码跑报错Traceback (most recent call last):
> > > File "F:\pandalearning.py", line 4, in
> > > from pdlearn import version
> > > File "F:\pdlearn\version.py", line 1, in
> > > import requests
> > > ModuleNotFoundError: No module named 'requests'
> > > 谁知道怎么回事？？
> > 
> > 
> > pip install requests 安装 requests
> > pip install selenium 安装 selenium
> > 再试试
> 
> 学习了...
> 自己打包exe成功，技能get

get就好！
