### ISSUE TITLE
mac出错

### ISSUE THREAD

**Issue by wangwangyh** [Alivon/Panda-Learning#231]
Traceback (most recent call last):
  File "pandalearning.py", line 181, in <module>
  File "pandalearning.py", line 49, in show_score
  File "pdlearn/score.py", line 14, in get_score
  File "pdlearn/score.py", line 14, in <listcomp>
TypeError: string indices must be integers
[5507] Failed to execute script pandalearning

**Comment by Going2333** [comment]
问之前看一下楼下几个帖子啊，看看别人怎么样了

**Comment by Alivon** [comment]
已修复
