### ISSUE TITLE
V2.5 发布，防js检测加强

### ISSUE THREAD

**Issue by Alivon** [Alivon/Panda-Learning#232]
# 修复强国网站更新导致的积分获取接口异常
##2.5以下版本无法使用，请及时更新

**Comment by liyuan97** [comment]
辛苦了

**Comment by Going2333** [comment]
感谢，更新后可以运行了。

**Comment by AnieliaO** [comment]
多谢！可以了。

**Comment by samway2005** [comment]
mac os版本升级到2.5，还是报错啊

**Comment by Going2333** [comment]
刚看到app里面有今天发布的公告，说是近期要进行产品升级，不知道到时候会不会又失效了

**Comment by asdqwe111** [comment]
Traceback (most recent call last):
  File "G:\waxx\4.12\pandalearning.py", line 8, in <module>
    from pdlearn import score
  File "G:\waxx\4.12\pdlearn\score.py", line 20
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xbb in position 15: invalid start byte

老哥，我全部复制你的源码，提示这玩意，是不是少了什么东西

**Comment by abc276033391** [comment]
大爱楼主。。

**Comment by asdqwe111** [comment]
![1111](https://user-images.githubusercontent.com/48905248/56020758-75f53000-5d3a-11e9-94b1-e8dc82924389.jpg)
作为一个强迫症晚期，我想问一下这些东西能不能想想办法让他别显示

**Comment by asdqwe111** [comment]
![1555055732(1)](https://user-images.githubusercontent.com/48905248/56021208-6fb38380-5d3b-11e9-82e2-37aaa32a1067.jpg)
强迫症晚期表示，这些东西能不能让他别显示。

**Comment by Alivon** [comment]
> ![1555055732(1)](https://user-images.githubusercontent.com/48905248/56021208-6fb38380-5d3b-11e9-82e2-37aaa32a1067.jpg)
> 强迫症晚期表示，这些东西能不能让他别显示。

直接最小化吧 😂

**Comment by Going2333** [comment]
> > ![1555055732(1)](https://user-images.githubusercontent.com/48905248/56021208-6fb38380-5d3b-11e9-82e2-37aaa32a1067.jpg)
> > 强迫症晚期表示，这些东西能不能让他别显示。
> 
> 直接最小化吧

...这办法不错

**Comment by abc276033391** [comment]
![QQ截图20190412165825](https://user-images.githubusercontent.com/48872453/56025267-5cf17c80-5d44-11e9-8d8f-e8ece1d8a916.jpg)
最后这一分就是学不上去，直接手机补上了，请问是啥原因导致的呀？

**Comment by icman02200459** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator.USER-20190326KT\.conda\envs\aaa\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\Administrator.USER-20190326KT\.conda\envs\aaa\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Administrator.USER-20190326KT\.conda\envs\aaa\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Administrator.USER-20190326KT/Desktop/Source Packages/pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "C:/Users/Administrator.USER-20190326KT/Desktop/Source Packages/pandalearning.py", line 21, in user_flag
    cookies = dingding.dd_login_status(uname)
  File "C:\Users\Administrator.USER-20190326KT\Desktop\Source Packages\pdlearn\dingding.py", line 23, in dd_login_status
    driver_login = mydriver.Mydriver(noimg=False)
  File "C:\Users\Administrator.USER-20190326KT\Desktop\Source Packages\pdlearn\mydriver.py", line 47, in __init__
    self.driver = self.webdriver.Chrome(chrome_options=self.options)
  File "C:\Users\Administrator.USER-20190326KT\.conda\envs\aaa\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Administrator.USER-20190326KT\.conda\envs\aaa\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

========================================================================================================================
Mydriver初始化失败
我运行源码，填写了手机号密码以后 就报错  什么原因

**Comment by yourgrass** [comment]
感谢，感谢！

**Comment by Alivon** [comment]
@abc276033391  应该是那条内容服务端错误

**Comment by wsjackys** [comment]
文章时长和视频时长可以正常学习，但是学习文章数量停在3/6就不动了，学习视频学习数量一直是0/6，重启了也不行，win10 64  版本2.5

**Comment by Liridice** [comment]
还是有一处报错：
[0413/002321.256:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.

**Comment by yz41** [comment]
我的是这个
[0413/012024.204:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.
能正常使用

**Comment by gantrylueng** [comment]
昨天更新了2.5用了一次。今天再用似乎用不了了。跟前几天一下，莫名错误很多就退出了

**Comment by Going2333** [comment]
刚才试了下，还可以用，不能用的是不是个别情况？我的win版本

**Comment by asdqwe111** [comment]
![77106c6e4bddfaa855f41c2804ff556](https://user-images.githubusercontent.com/48905248/56130378-49018100-5fb7-11e9-94f0-e11b295aa7cf.png)
今天下午好像更新了，赶快看一下

**Comment by mr-zl** [comment]
请教大佬，树莓派怎么更新？

**Comment by JunIce** [comment]
@mr-zl 重新下载吧

**Comment by HaishuoFang** [comment]
@Alivon ,我要是想设置代理ip,就不能用headless模式是吧,chrome driver是不是不支持？有什么方法设置带验证的代理呢？

**Comment by kingwu1984** [comment]
好像又需要更新了

**Comment by HaishuoFang** [comment]
有人有文章学习和视频学习一直在相互跳转的情况么

**Comment by Andrew-Hello** [comment]
[0413/002321.256:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid: Missing track ID in msid attribute.
之后程序闪退

**Comment by lpc1230** [comment]
Mydriver初始化失败======================
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "pandalearning.py", line 21, in user_flag
    cookies = dingding.dd_login_status(uname)
  File "/root/pdlearn/dingding.py", line 23, in dd_login_status
    driver_login = mydriver.Mydriver(noimg=False)
  File "/root/pdlearn/mydriver.py", line 47, in __init__
    self.driver = self.webdriver.Chrome(chrome_options=self.options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

输入账号密码就有这个显示出来，什么情况？

**Comment by 1053203144** [comment]
涉嫌违规，封号7天，这个开始封号了

**Comment by initialall** [comment]
> > ![1555055732(1)](https://user-images.githubusercontent.com/48905248/56021208-6fb38380-5d3b-11e9-82e2-37aaa32a1067.jpg)
> > 强迫症晚期表示，这些东西能不能让他别显示。
> 
> 直接最小化吧

请教下这是什么原因导致的?
