### ISSUE TITLE
直接从源文件pandalearning.py运行出错

### ISSUE THREAD

**Issue by sbw983** [Alivon/Panda-Learning#237]
$ python3 pandalearning.py 
Traceback (most recent call last):
  File "pandalearning.py", line 6, in <module>
    from pdlearn import dingding
  File "/home/sbw983/tmp/Fuck-Qiangguo/Panda-Learning-2.5/Source Packages/pdlearn/dingding.py", line 2, in <module>
    from pdlearn import mydriver
  File "/home/sbw983/tmp/Fuck-Qiangguo/Panda-Learning-2.5/Source Packages/pdlearn/mydriver.py", line 1, in <module>
    from selenium import webdriver
ImportError: No module named 'selenium'

$python3 --version
Python 3.5.2

Panda-Learning V2.5

在ubuntu 16.04和windows上报错信息相同

**Comment by liudidi** [comment]
pip3 install selenium

**Comment by fuckthegit** [comment]
源码运行需要手动安装 selenium 和 requests：
```
pip install selenium
pip install requests
```

**Comment by sbw983** [comment]
谢谢解答，已解决
