### ISSUE TITLE
老大，视频不能学习，却自动结束了

### ISSUE THREAD

**Issue by 85524365** [Alivon/Panda-Learning#253]
DevTools listening on ws://127.0.0.1:55715/devtools/browser/305dd1ca-6b1c-47ef-9d54-e5ed4e9035f5
视频学习中，视频剩余6个,本次剩余时间1秒 当前学习总积分：636
阅读文章:6/6,观看视频:1/6,登陆:1/1,文章时长:6/6,视频时长:0/6
Exception in thread 视频学习:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "pdlearn\threads.py", line 20, in run
  File "pandalearning.py", line 125, in video
  File "pdlearn\mydriver.py", line 119, in get_url
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17763 x86_64)

总计用时22.4分钟
无自动关机任务，已释放程序内存，10分钟后窗口将自动关闭

C:\Program Files\Panda_learning-32>

**Comment by herocspx** [comment]
刚试了，运行正常。没有问题。

**Comment by Alivon** [comment]
查看 #256
