### ISSUE TITLE
ubuntu 报错 TypeError: string indices must be integers

### ISSUE THREAD

**Issue by CS2JOONGKI** [Alivon/Panda-Learning#255]
```
Traceback (most recent call last):
  File "pandalearning.py", line 177, in <module>
  File "pandalearning.py", line 49, in show_score
  File "pdlearn/score.py", line 14, in get_score
  File "pdlearn/score.py", line 14, in <listcomp>
TypeError: string indices must be integers
[4736] Failed to execute script pandalearning
```
运行Ubuntu运行最新2.5报错

**Comment by EmonLieu** [comment]
强国更新积分规则应该
