### ISSUE TITLE
mac用终端显示Mydriver初始化失败请问如何解决

### ISSUE THREAD

**Issue by wongchencool** [Alivon/Panda-Learning#266]
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "selenium/webdriver/common/service.py", line 76, in start
  File "subprocess.py", line 729, in __init__
  File "subprocess.py", line 1364, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn/dingding.py", line 23, in dd_login_status
  File "pdlearn/mydriver.py", line 47, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 73, in __init__
  File "selenium/webdriver/common/service.py", line 83, in start
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

[9957] Failed to execute script pandalearning
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by wongchencool** [comment]
看到了终端运行……可是我不会终端运行呀，请问输入什么样的指令才能终端运行？我把那个文件拖进终端去好像也不行

**Comment by Aires-666** [comment]
打开终端
输入cd
把pandalearning_macos整个文件夹拖进终端
回车
输入./pandalearning
回车

**Comment by Tochase** [comment]
![image](https://user-images.githubusercontent.com/15307280/56634496-c8b4dd00-6694-11e9-8e9a-a0fc93d1cbe9.png)
同样的问题

**Comment by kalasusen** [comment]
下载对应版本chromedriver，放入,BIN文件夹即可

**Comment by Tochase** [comment]
> 下载对应版本chromedriver，放入,BIN文件夹即可

感谢，我这边用72版本的chromedriver替换之后，可以正常运行了。下附相关信息，供其他人参考。

报错信息：
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.14.4 x86_64)
程序版本：v2.5
平台：mac os

**Comment by jaycn06010** [comment]
> 下载对应版本chromedriver，放入,BIN文件夹即可

bin文件夹在哪？
