### ISSUE TITLE
MAC 下launchctl 运行报错

### ISSUE THREAD

**Issue by mercurialy** [Alivon/Panda-Learning#278]
[24992] Failed to execute script pandalearning
Exception in thread \u83b7\u53d6\u66f4\u65b0\u4fe1\u606f...:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "pdlearn/threads.py", line 17, in run
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 15, in user_flag
  File "pdlearn/dingding.py", line 20, in dd_login_status
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)

MAC 下直接运行可以，使用 launchctl 调用报错

**Comment by liangdl** [comment]
一开始我用crontab /目录/pandalearning user1 这种格式也是出现你这个提示
后来改成cd /目录 && ./pandalearning user1就能执行了，但是现在问题是卡在下面这里不动了。
更新显示不会打断之前输入等操作，请继续......（若已输入用户标记直接enter）
