### ISSUE TITLE
更新Chrome以及Chromedriver后不能启动

### ISSUE THREAD

**Issue by suda-morris** [Alivon/Panda-Learning#294]
Chrome的版本：版本 74.0.3729.108（正式版本） （64 位）
Chromedriver的版本：74.0.3729.6，从[这里](http://npm.taobao.org/mirrors/chromedriver)下载来的
完整的报错信息如下：
```bash
========================================================================================================================
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn/dingding.py", line 23, in dd_login_status
  File "pdlearn/mydriver.py", line 39, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 81, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 157, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 252, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.18.0-18-generic x86_64)

[7087] Failed to execute script pandalearning
```

**Comment by Alivon** [comment]
下载对应操作系统的 ，linux和windows以及mac都不同

**Comment by linhaii** [comment]
我从chromium官网下载的最新74的chromedriver，替换的原来的。

**Comment by kalasusen** [comment]
74的不行，下载73版本的chrome和drivers即可，将driver放入bin，详见之前的帖子

**Comment by linhaii** [comment]
不就是根目录吗？整个目录就两个文件，以及生成的存储用户信息的文件夹。我能启动，但是遇到了 #293 的问题
