### ISSUE TITLE
ubuntu安装好google-chrome-stable_current_amd64.deb,执行后pandalearning出错

### ISSUE THREAD

**Issue by yegeziz** [Alivon/Panda-Learning#295]
root@ubuntu1:/home# ./pandalearning
Exception in thread \u83b7\u53d6\u66f4\u65b0\u4fe1\u606f...:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "pdlearn/threads.py", line 17, in run
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

Traceback (most recent call last):
  File "pandalearning.py", line 179, in <module>
  File "pdlearn/user.py", line 10, in get_user
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
[7338] Failed to execute script pandalearning

**Comment by lostinfever** [comment]
设置系统环境变量为UTF-8即可

**Comment by lemonzlm** [comment]
不行呢，设了也没用呢
