### ISSUE TITLE
win10系统下chrome更新74后也运行不了了

### ISSUE THREAD

**Issue by tl1cn** [Alivon/Panda-Learning#296]
开启： 获取更新信息...

正在联网获取更新信息...读取用户信息成功

========================================================================================================================
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 15, in user_flag
  File "pdlearn\dingding.py", line 23, in dd_login_status
  File "pdlearn\mydriver.py", line 36, in __init__
  File "lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location ./chrome/chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17134 x86_64)

[3324] Failed to execute script pandalearning

**Comment by laoqiuqiu** [comment]
me too

**Comment by lostinfever** [comment]
chrome更新后，chromedriver也要同步更新

**Comment by tl1cn** [comment]
我下了最新的chromedriver，替换了自带的E:\Panda_learning-32\chrome下的chromedriver，也不行，直接闪退，Panda_learning-32自带的是73的chrome

**Comment by tl1cn** [comment]
> 铬更新后，chromedriver也要同步更新

怎么同步更新？

**Comment by laoqiuqiu** [comment]
我的是73
出现这个错误
DevTools listening on ws://127.0.0.1:49215/devtools/browser/2fa13fec-120c-44f2-a393-72b79b05f7f5
[0428/103859.101:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0428/103859.101:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0428/103859.102:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0428/103859.102:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0428/103859.102:ERROR:rtc_peer_connection_handler.cc(2225)] Failed to create native session description. Type: offer SDP: v=0
o=- 4428428034655679244 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS
m=application 9 UDP/TLS/RTP/SAVPF 119
c=IN IP4 0.0.0.0
b=AS:30
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:h3Z+
a=ice-pwd:ajiS693hZiG+RjlusbmKb5CZ
a=ice-options:trickle
a=fingerprint:sha-256 0D:E2:0E:DD:A1:C4:8B:7B:B2:9A:63:2C:3C:0F:14:26:5F:1F:5E:50:7F:CB:F9:E8:DA:53:ED:EC:DB:2C:40:85
a=setup:actpass
a=mid:0
a=sendrecv
a=msid:
a=rtcp-mux
a=rtpmap:119 google-data/90000
a=ssrc:3671015580 cname:7nrfOD86ftWIMYKo
a=ssrc:3671015580 msid:-
a=ssrc:3671015580 mslabel:-
a=ssrc:3671015580 label:

[0428/103859.102:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.
登陆中...
----------
[0428/103934.704:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Failed to send audio packet for decoding: timestamp=0 duration=23220 size=232 side_data_size=0 is_key_frame=1 encrypted=0 discard_padding (us)=(46439, 0)"}
[0428/103934.705:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio decoder reinitialization failed"}
[0428/103934.705:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
[0428/103934.705:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR PIPELINE_ERROR_DECODE
[0428/103934.706:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Failed to send video packet for decoding: timestamp=86440 duration=40000 size=26 side_data_size=0 is_key_frame=0 encrypted=0 discard_padding (us)=(0, 0)"}
[0428/103934.707:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decoder reinitialization failed"}

**Comment by GPPyeye** [comment]
mydriver 更新一下就行了。亲测可以，但是不能加速学习了
