### ISSUE TITLE
斐讯N1自动化学习的Docker镜像

### ISSUE THREAD

**Issue by lostinfever** [Alivon/Panda-Learning#297]
话不多说，详见：
https://hub.docker.com/r/lostinfever/arrch64-ubuntu-pandalearning

**Comment by noway2014** [comment]
不是一般人能做得到呀。有更加简单的方法吗

**Comment by lostinfever** [comment]
> 不是一般人能做得到呀。有更加简单的方法吗

docker已经是最简单的方式了，我写的足够详细了，基本上新手也做得到吧

**Comment by Alivon** [comment]
很棒，看到你说占用500M内存似乎用不了这么多 我用vps跑源码好像几十到上百m内存占用，是设备性能导致的吗

**Comment by lostinfever** [comment]
``
> 很棒，看到你说占用500M内存似乎用不了这么多 我用vps跑源码好像几十到上百m内存占用，是设备性能导致的吗

我也很疑惑，设备是4线程的，我用分别用single参数和不加single参数运行源码：
单线程：chromedriver共有6个线程，chromium-browser更是有40多个线程，内存占用在200m左右；
双线程：chromedriver共有12个线程，chromium-browser更是有80多个线程，内存占用在400m左右；

**Comment by lostinfever** [comment]
我估计是chromium的参数没有优化吧，按理说跑2个网页不至于有这么多的内存占用啊

**Comment by gqyun88** [comment]
已经设置好，就等明天早晨5:00检验下成果啦，嘻嘻

**Comment by gqyun88** [comment]
get_video_links获取失败???所有的视频学习失败

**Comment by shen159876** [comment]
crontab有某个时间点延迟随机时间学习的功能吗，比如说5点执行，延迟600s随机开始

**Comment by lostinfever** [comment]
把命令写入sh脚本，前面加上：

sleep $RANDOM%600+300


简单说明一下：
$RANDOM%600 
产生0-599的随机数字

$RANDOM%600+300
产生300-899的随机数字

以此类推获取你想要的随机范围

**Comment by shen159876** [comment]
> 把命令写入sh脚本，前面加上：
> 
> sleep $RANDOM%600+300
> 
> 简单说明一下：
> $RANDOM%600
> 产生0-599的随机数字
> 
> $RANDOM%600+300
> 产生300-899的随机数字
> 
> 以此类推获取你想要的随机范围

好的，我测试一下，多谢了

**Comment by shen159876** [comment]
镜像文件可以提供下载吗？
我直接pull，下了2小时都还差300MB没下载完，连接速度很慢

**Comment by lostinfever** [comment]
玩这个没有梯子怎么能行，镜像是多个分段合成的，单独传也不方便

**Comment by shen159876** [comment]
> 玩这个没有梯子怎么能行，镜像是多个分段合成的，单独传也不方便

用了全局代理，然后速度还是很慢，可能是梯子质量不太好

**Comment by xin8157** [comment]
这个docker 可以在群晖的docker里面运行吗？菜鸟弱弱的问一下

**Comment by gqyun88** [comment]
> 这个docker 可以在群晖的docker里面运行吗？菜鸟弱弱的问一下

不能，要适配后才能食用

**Comment by shen159876** [comment]
> 把命令写入sh脚本，前面加上：
> 
> sleep $RANDOM%600+300
> 
> 简单说明一下：
> $RANDOM%600
> 产生0-599的随机数字
> 
> $RANDOM%600+300
> 产生300-899的随机数字
> 
> 以此类推获取你想要的随机范围

实际测试了一下，如果延时的话，需要加一个$才能运行
比如这样
sleep $(($RANDOM%3000+2))
还有一个遇到的小问题，就是ASCII的编码要添加一个export PYTHONIOENCODING=UTF-8 才能正常运行。

**Comment by aiwieyang** [comment]
在Docker里创建一个虚拟网段 这个要怎么操作呢

**Comment by wanglz111** [comment]
@aiwieyang 
docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o parent=eth0 macnet
这步就是 第一个参数192.168.1.0/24改成你自己路由器的网段 比如你路由器控制台是192.168.2.1 这里就改成192.168.2.0/24
那个gateway同理

**Comment by sunbeam5** [comment]
执行到第四步时总是出问题，重装问题依旧，能帮忙看一下吗。
```cd /media/pdlearning && python3 -u pandalearning.py
开启： 获取更新信息...
输入用户标记名：
正在联网获取更新信息...
版本信息网络错误
   
是否保存钉钉帐户密码，保存后可后免登陆学习(Y/N) y
请输入正确的学习强国帐号(钉钉手机号)：180*****
请输入学习强国密码：2b*****
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "pandalearning.py", line 21, in user_flag
    cookies = dingding.dd_login_status(uname)
  File "/media/pdlearning/pdlearn/dingding.py", line 24, in dd_login_status
    login_status = driver_login.dd_login(dname, pwd)
  File "/media/pdlearning/pdlearn/mydriver.py", line 95, in dd_login
    self.driver.find_elements_by_id("mobilePlaceholder")[0].click()
lIndexError: list index out of range```
