### ISSUE TITLE
ubuntu下报运行不了

### ISSUE THREAD

**Issue by GeekCatPYG** [Alivon/Panda-Learning#30]
ubuntu下报这个错，我不知道是我系统的问题还是其它原因
请输入用户名:XXX
Traceback (most recent call last):
  File "selenium/webdriver/common/service.py", line 76, in start
  File "subprocess.py", line 947, in __init__
  File "subprocess.py", line 1551, in _execute_child
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearn.py", line 217, in <module>
  File "selenium/webdriver/chrome/webdriver.py", line 73, in __init__
  File "selenium/webdriver/common/service.py", line 88, in start
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

[3463] Failed to execute script pandalearn

**Comment by GeekCatPYG** [comment]
修改权限后报错：
请输入用户名:XXX
Traceback (most recent call last):
  File "pandalearn.py", line 217, in <module>
  File "selenium/webdriver/chrome/webdriver.py", line 81, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 157, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 252, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.18.0-15-generic x86_64)

[3720] Failed to execute script pandalearn

**Comment by Alivon** [comment]
请确认chromedriver文件是否在当前目录

**Comment by GeekCatPYG** [comment]
我是下载后直接解压出来用，chromedriver、pandalearn在同一目录中，我把这两个文件放在放在桌面

**Comment by Alivon** [comment]
> 我是下载后直接解压出来用，chromedriver、pandalearn在同一目录中，我把这两个文件放在放在桌面

检查Chrome是否安装好，其他自能自己阅读使用方案解决了，测试过是能运行的

**Comment by xenonum** [comment]
Traceback (most recent call last):
  File "pandalearning.py", line 176, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn/dingding.py", line 23, in dd_login_status
  File "pdlearn/mydriver.py", line 22, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 81, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 157, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 252, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.15.0-47-generic x86_64)
