### ISSUE TITLE
无法登陆，什么原因？

### ISSUE THREAD

**Issue by easthot2000** [Alivon/Panda-Learning#301]
C:\Users\Administrator\Desktop\Panda_learning-32\chrome>pandalearning.exe chen s
how single
开启： 获取更新信息...

正在联网获取更新信息...
读取用户信息成功

DevTools listening on ws://127.0.0.1:65531/devtools/browser/b74984df-283a-4028-b
6e0-a6ac2631deb2
熊猫学习唯一下载地址为 https://github.com/Alivon/Panda-Learning
程序版本为：v2.5，
最新版本为：v2.5
================================================================================
========================================
================================================================================
========================================
更新显示不会打断之前输入等操作，请继续......（若已输入用户标记直接enter）
[0429/134854.871:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason:
Missing track ID in msid attribute.
[0429/134854.872:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason:
Missing track ID in msid attribute.
[0429/134854.872:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason:
Missing track ID in msid attribute.
[0429/134854.873:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason:
Missing track ID in msid attribute.
[0429/134854.873:ERROR:rtc_peer_connection_handler.cc(2225)] Failed to create na
tive session description. Type: offer SDP: v=0
o=- 5239981475260060064 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS
m=application 9 UDP/TLS/RTP/SAVPF 119
c=IN IP4 0.0.0.0
b=AS:30
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:eZkg
a=ice-pwd:EI9Tb8T+ht9PWeZrsICDIb2T
a=ice-options:trickle
a=fingerprint:sha-256 D4:D8:5E:12:06:29:CB:84:BC:41:72:0D:C7:BF:0A:92:AF:49:A4:E
7:C2:7B:E3:5E:D3:8A:D1:9A:00:4F:1A:E2
a=setup:actpass
a=mid:0
a=sendrecv
a=msid:
a=rtcp-mux
a=rtpmap:119 google-data/90000
a=ssrc:3576519013 cname:7seMYDvus4vPrtLJ
a=ssrc:3576519013 msid:-
a=ssrc:3576519013 mslabel:-
a=ssrc:3576519013 label:

[0429/134854.874:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse Ses
sionDescription. a=msid:  Missing track ID in msid attribute.
登陆中...
================================================================================
========================================
get_video_links获取失败
================================================================================
========================================
Traceback (most recent call last):
  File "pandalearning.py", line 181, in <module>
  File "pandalearning.py", line 49, in show_score
  File "pdlearn\score.py", line 12, in get_score
TypeError: 'NoneType' object is not subscriptable
[19008] Failed to execute script pandalearning

C:\Users\Administrator\Desktop\Panda_learning-32\chrome>pause
请按任意键继续. . .

**Comment by easthot2000** [comment]
补充一下，不用钉钉登录，用二维码登录就可以用了，什么原因？

**Comment by zb63fhxx** [comment]
我也遇到一样的问题了

**Comment by zb63fhxx** [comment]
怎么用二维码登录的？？

**Comment by zb63fhxx** [comment]
会了，先救急用。感谢

**Comment by jxzzy** [comment]
你的钉钉跟强国的密码不一样，改成一样的

**Comment by easthot2000** [comment]
> 你的钉钉跟强国的密码不一样，改成一样的

密码是一样的。

**Comment by Andrew-Hello** [comment]
我也出现了，换不同电脑情况依旧。2.3是可以用的，2.5不行了
