### ISSUE TITLE
今上午出现错误，请问如何解决呢？谢谢！

### ISSUE THREAD

**Issue by hououinkami** [Alivon/Panda-Learning#308]
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 18, in user_flag
  File "pdlearn/mydriver.py", line 39, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 81, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 157, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 252, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.14.4 x86_64)

[4632] Failed to execute script pandalearning

**Comment by hongm328** [comment]
你的浏览器更新了，你需要同时更新chromedriver

**Comment by hououinkami** [comment]
> 你的浏览器更新了，你需要同时更新chromedriver

请问如何更新呢？

**Comment by hongm328** [comment]
> > 你的浏览器更新了，你需要同时更新chromedriver
> 
> 请问如何更新呢？

可以去http://npm.taobao.org/mirrors/chromedriver/下载相应版本的chromedriver覆盖

**Comment by hououinkami** [comment]
> > > 你的浏览器更新了，你需要同时更新chromedriver
> > 
> > 
> > 请问如何更新呢？
> 
> 可以去
> http://npm.taobao.org/mirrors/chromedriver/
> 下载相应版本的chromedriver覆盖

非常感谢！

**Comment by acai66** [comment]
百度找禁用macos chrome自动更新的教程
