### ISSUE TITLE
手机上安装在Ubuntu 但是无法使用

### ISSUE THREAD

**Issue by aiwieyang** [Alivon/Panda-Learning#325]
出现这个问题要怎么解决呢？
mydriver 初始化失败

**Comment by aiwieyang** [comment]
Mydriver初始化失败                              ========================================================================================================================                        Traceback (most recent call last):                File "pandalearning.py", line 180, in <module>    cookies, a_log, v_log = user_flag(dd_status, uname)                                           File "pandalearning.py", line 21, in user_flag    cookies = dingding.dd_login_status(uname)     File "/root/pdlearn/dingding.py", line 23, in dd_login_status                                     driver_login = mydriver.Mydriver(noimg=False)                                                 File "/root/pdlearn/mydriver.py", line 39, in __init__                                            chrome_options=self.options)                  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__                                        desired_capabilities=desired_capabilities)    File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__                                       self.start_session(capabilities, browser_profile)                                             File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session                                  response = self.execute(Command.NEW_SESSION, parameters)                                      File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute                                        self.error_handler.check_response(response)   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response                              raise exception_class(message, screen, stac

**Comment by aiwieyang** [comment]
@AthenaCN

**Comment by aiwieyang** [comment]
@Alivon

**Comment by Alivon** [comment]
依赖库和chromedriver都装好了吗？

**Comment by aiwieyang** [comment]
@Alivon 已安装，但是提示上面错误信息，谢谢老哥帮忙看看

**Comment by Going2333** [comment]
我也是按照教程一步步来，要学习的时候提示mydriver 初始化失败

**Comment by SpikerA** [comment]
> 我也是按照教程一步步来，要学习的时候提示 mydriver 初始化失败

重新安装呀，我以前挂VPN的时候切换节点了，导致有些文件没有下载到

**Comment by wrather70** [comment]
同出现这个问题，重新按照操作步骤重装无效。
