### ISSUE TITLE
求问这个报错是什么原因？ 谢谢

### ISSUE THREAD

**Issue by PaoloWind** [Alivon/Panda-Learning#333]
DevTools listening on ws://127.0.0.1:6274/devtools/browser/6eedaf8c-ce7f-474f-94
74-7e79700edd8c
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn\dingding.py", line 24, in dd_login_status
  File "pdlearn\mydriver.py", line 95, in dd_login
IndexError: list index out of range
[3992] Failed to execute script pandalearning

**Comment by 215516140** [comment]
啊啊啊我也是这个错

**Comment by szxyes** [comment]
我的也是报错，不过我的是这个
Exception in thread 视频学习:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "pdlearn\threads.py", line 23, in run
  File "pandalearning.py", line 118, in video
  File "pdlearn\mydriver.py", line 116, in set_cookies
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 894, in add_cookie
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.UnableToSetCookieException: Message: unable to set cookie
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17763 x86_64)

Exception in thread 文章学习:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "pdlearn\threads.py", line 23, in run
  File "pandalearning.py", line 59, in article
  File "pdlearn\mydriver.py", line 116, in set_cookies
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 894, in add_cookie
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.UnableToSetCookieException: Message: unable to set cookie
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17763 x86_64)

**Comment by a2008zhang** [comment]
我的目前能正常使用

**Comment by lenmao** [comment]
> DevTools listening on ws://127.0.0.1:6274/devtools/browser/6eedaf8c-ce7f-474f-94
> 74-7e79700edd8c
> Traceback (most recent call last):
> File "pandalearning.py", line 180, in 
> File "pandalearning.py", line 21, in user_flag
> File "pdlearn\dingding.py", line 24, in dd_login_status
> File "pdlearn\mydriver.py", line 95, in dd_login
> IndexError: list index out of range
> [3992] Failed to execute script pandalearning

关了重启动试下，我遇到这情况直接挂个代理重启动立即正常。再试下正常把代理关了后开启试下

**Comment by qlcyl110** [comment]
DevTools listening on ws://127.0.0.1:50095/devtools/browser/ee2e9c1e-8bc7-4709-b
a64-0bf81116bccc
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 15, in user_flag
  File "pdlearn\dingding.py", line 24, in dd_login_status
  File "pdlearn\mydriver.py", line 95, in dd_login
IndexError: list index out of range
[4760] Failed to execute script pandalearning

**Comment by xfrose** [comment]
[2331] Failed to execute script pandalearning
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 15, in user_flag
  File "pdlearn/dingding.py", line 24, in dd_login_status
  File "pdlearn/mydriver.py", line 95, in dd_login
IndexError: list index out of range

我也一样

**Comment by qq275164185** [comment]
> > DevTools listening on ws://127.0.0.1:6274/devtools/browser/6eedaf8c-ce7f-474f-94
> > 74-7e79700edd8c
> > Traceback (most recent call last):
> > File "pandalearning.py", line 180, in
> > File "pandalearning.py", line 21, in user_flag
> > File "pdlearn\dingding.py", line 24, in dd_login_status
> > File "pdlearn\mydriver.py", line 95, in dd_login
> > IndexError: list index out of range
> > [3992] Failed to execute script pandalearning
> 
> 关了重启动试下，我遇到这情况直接挂个代理重启动立即正常。再试下正常把代理关了后开启试下

代理怎么关
