### ISSUE TITLE
今天跳出一个新问题，能正常登陆但不自动学习

### ISSUE THREAD

**Issue by yanhcl** [Alivon/Panda-Learning#335]
Exception in thread 文章学习:
Traceback (most recent call last):
  File "D:\Python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\Desktop\Panda-Learning-2.5\Source Packages\pdlearn\threads.py", line 23, in run
    self.func(*self.args)
  File "C:/Users/Administrator/Desktop/Panda-Learning-2.5/Source Packages/pandalearning.py", line 66, in article
    driver_article.get_url(links[i])
  File "C:\Users\Administrator\Desktop\Panda-Learning-2.5\Source Packages\pdlearn\mydriver.py", line 119, in get_url
    self.driver.get(url)
  File "D:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "D:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 6.1.7601 SP1 x86_64)

Exception in thread 视频学习:
Traceback (most recent call last):
  File "D:\Python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\Desktop\Panda-Learning-2.5\Source Packages\pdlearn\threads.py", line 23, in run
    self.func(*self.args)
  File "C:/Users/Administrator/Desktop/Panda-Learning-2.5/Source Packages/pandalearning.py", line 126, in video
    time.sleep(random.randint(5, 15))
  File "C:\Users\Administrator\Desktop\Panda-Learning-2.5\Source Packages\pdlearn\mydriver.py", line 119, in get_url
    self.driver.get(url)
  File "D:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "D:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by lenmao** [comment]
重启电脑换时间段试下。
直接虚拟机装了个debian，好好的着
