### ISSUE TITLE
5.27  不能学习，Mydriver初始化失败

### ISSUE THREAD

**Issue by 85524365** [Alivon/Panda-Learning#354]
正在联网获取更新信息...
读取用户信息成功
熊猫学习唯一下载地址为 https://github.com/Alivon/Panda-Learning
程序版本为：v2.5，
最新版本为：v2.5
================================================================================
========================================
================================================================================
========================================
更新显示不会打断之前输入等操作，请继续......（若已输入用户标记直接enter）
================================================================================
========================================
Mydriver初始化失败
================================================================================
========================================
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 15, in user_flag
  File "pdlearn\dingding.py", line 23, in dd_login_status
  File "pdlearn\mydriver.py", line 36, in __init__
  File "lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in _
_init__
  File "lib\site-packages\selenium\webdriver\common\service.py", line 104, in st
art
selenium.common.exceptions.WebDriverException: Message: Can not connect to the S
ervice ./chrome/chromedriver.exe

[11072] Failed to execute script pandalearning

C:\Program Files\Panda_learning-32>

**Comment by jonkony** [comment]
我也是，可能不能学了，一上来全是封号的。现在单位也没那么严了，不学了

**Comment by jzmswe** [comment]
请提问用户填写相关信息，帮助作者排查故障，如有需要增加的项，也请指出

使用的客户端： Windows MacOS Linux VPS Raspbian-pi
是否开启多线程： 是 否 不清楚
登录方式： 二维码 账号密码
使用频率： 每天 大部分 偶尔 极少
同一时间启动用户数： 单个用户 2~5 6~10 10~20 20+
是否隐藏窗口： 是 否 不清楚
是否每天准时启动： 是 否 不清楚
封禁类型： 7天封禁+积分没动 7天封禁+积分清空 永久封禁 其他（自行填写）
