### ISSUE TITLE
关于文章无法阅读的解决方案

### ISSUE THREAD

**Issue by jackysnoopy** [Alivon/Panda-Learning#403]
昨天强国官网的文章阅读用软件已经不能加分了，分析数据后发现文章列表信息有变换，使用原来的文章列表拉去的文章阅读后不加分，大家可以直接修改get_links.py文件get_article_links方法修改方案如下：
 try:
        url = "https://www.xuexi.cn/lgdata/1crqb964p71.json"
        str=requests.get(url)
        strList=str.json()
        links=[]
        for i in strList:
            links.append(i['url'])
        return links
    except:
        print("=" * 120)
        print("get_article_links获取失败")
        print("=" * 120)
        raise

**Comment by jzmswe** [comment]
> 昨天强国官网的文章阅读用软件已经不能加分了，分析数据后发现文章列表信息有变换，使用原来的文章列表拉去的文章阅读后不加分，大家可以直接修改get_links.py文件get_article_links方法修改方案如下：
> try:
> url = "https://www.xuexi.cn/lgdata/1crqb964p71.json"
> str=requests.get(url)
> strList=str.json()
> links=[]
> for i in strList:
> links.append(i['url'])
> return links
> except:
> print("=" * 120)
> print("get_article_links获取失败")
> print("=" * 120)
> raise

用everything找不到get_links.py文件

**Comment by jackysnoopy** [comment]
要用源代码，共享的7z文件里面都是已经编译好的程序，需要下载源代码后用python重新执行

**Comment by jzmswe** [comment]
> 要用源代码，共享的7z文件里面都是已经编译好的程序，需要下载源代码后用python重新执行

能否1、2、3、4步骤说一下，打开哪个文件，用python 3.5还是哪个版本打开。不要说原理，只说操作步骤即可。多谢！
虽然感觉可能性不大（你觉得麻烦），但万一呢。

**Comment by jackysnoopy** [comment]
1 下载源文件
2 将7Z解压中的chome文件夹和原来的user文件夹拷贝到Source Packages文件夹，在此文件夹中可以看到pandalearning.py文件
3 进入pdlearn文件夹修改get_links.py文件
4 cmd进入控制台，进入Source Packages文件夹 运行python pandalearning.py 用户名（即原来user文件夹保存的用户信息）

**Comment by jackysnoopy** [comment]
追踪HTTP协议后发现在json请求后有个时间戳信息，估计是用来抓刷机的，现将带时间戳的请求修改如下（还是修改get_links.py文件，暂时修改文章列表获取方法，估计不久视频列表也会发生变化）：
import requests
import re
import time
def get_article_links():
    try:
        t_str=int(time.time()/60)
        url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str)
        str=requests.get(url)
        strList=str.json()
        links=[]
        for i in strList:
            links.append(i['url'])
        return links

    except:
        print("=" * 120)
        print("get_article_links获取失败")
        print("=" * 120)
        raise

**Comment by xuxudong1110** [comment]
按照方案这这么报错的无法运行
Traceback (most recent call last):
  File "pandalearning.py", line 4, in <module>
    from pdlearn import version
  File "D:\Source Packages\pdlearn\version.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by freessrnet3vnet** [comment]
这个是什么情况？楼上的No module named requests需要用pip install requests安装一下

================================================================================
========================================
Mydriver初始化失败
================================================================================
========================================
Traceback (most recent call last):
  File "D:\Program Files\Python37\lib\site-packages\selenium\webdriver\common\se
rvice.py", line 76, in start
    stdin=PIPE)
  File "D:\Program Files\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\Program Files\Python37\lib\subprocess.py", line 1178, in _execute_chi
ld
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Panda-Learning-master\SourcePackages\pandalearning.py", line 1
80, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "D:\python\Panda-Learning-master\SourcePackages\pandalearning.py", line 2
1, in user_flag
    cookies = dingding.dd_login_status(uname)
  File "D:\python\Panda-Learning-master\SourcePackages\pdlearn\dingding.py", lin
e 23, in dd_login_status
    driver_login = mydriver.Mydriver(noimg=False)
  File "D:\python\Panda-Learning-master\SourcePackages\pdlearn\mydriver.py", lin
e 47, in __init__
    self.driver = self.webdriver.Chrome(chrome_options=self.options)

**Comment by jackysnoopy** [comment]
缺少python的依赖报 建议百度看解决方案，除了requests包好像还要引入几个包 他报什么就装什么

**Comment by freessrnet3vnet** [comment]
編譯了一個windows版本的，當前測試還能用
https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning2.exe

**Comment by sunzp21** [comment]
代码有问题，第8行你把关键字str赋值了，会报错

> 追踪HTTP协议后发现在json请求后有个时间戳信息，估计是用来抓刷机的，现将带时间戳的请求修改如下（还是修改get_links.py文件，暂时修改文章列表获取方法，估计不久视频列表也会发生变化）：
> 
> ```
> import requests
> import re
> import time
> def get_article_links():
>     try:
>         t_str=int(time.time()/60)
>         url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str)
>         str=requests.get(url)
>         strList=str.json()
>         links=[]
>         for i in strList:
>             links.append(i['url'])
>         return links
> 
>     except:
>         print("=" * 120)
>         print("get_article_links获取失败")
>         print("=" * 120)
>         raise
> ```

**Comment by lili205** [comment]
> 编译了一个窗口版本的，测试当前还能用
> https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning2.exe

无法下载啊，说是文件太大了

**Comment by freessrnet3vnet** [comment]
> > 编译了一个窗口版本的，测试当前还能用
> > https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning2.exe
> 
> 无法下载啊，说是文件太大了
7.01m
https://github.com/freessrnet3vnet/xuexiqiangguo/raw/master/pandalearning2.exe

**Comment by logique233** [comment]
> > > 编译了一个窗口版本的，测试当前还能用
> > > https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning2.exe
> > 
> > 
> > 无法下载啊，说是文件太大了
> > 7.01m
> > https://github.com/freessrnet3vnet/xuexiqiangguo/raw/master/pandalearning2.exe

阅读文章:1/6,观看视频:6/6,登陆:1/1,文章时长:4/6,视频时长:6/6
Exception in thread 文章学习:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "pdlearn\threads.py", line 23, in run
  File "pandalearning.py", line 66, in article
IndexError: list index out of range

总计用时3.033333333333333分钟

出错了

**Comment by freessrnet3vnet** [comment]
> > > > 编译了一个窗口版本的，测试当前还能用
> > > > https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning2.exe
> > > 
> > > 
> > > 无法下载啊，说是文件太大了
> > > 7.01m
> > > https://github.com/freessrnet3vnet/xuexiqiangguo/raw/master/pandalearning2.exe
> 
> 阅读文章:1/6,观看视频:6/6,登陆:1/1,文章时长:4/6,视频时长:6/6
> Exception in thread 文章学习:
> Traceback (most recent call last):
> File "threading.py", line 917, in _bootstrap_inner
> File "pdlearn\threads.py", line 23, in run
> File "pandalearning.py", line 66, in article
> IndexError: list index out of range
> 
> 总计用时3.033333333333333分钟
> 
> 出错了
大神的程序有问题，用的第一个方案，第二个方案有错。

**Comment by freessrnet3vnet** [comment]
粘貼代碼的時候格式錯誤，造成list就一個地址，哈哈，初學者，sorry。下面改正了一下
https://github.com/freessrnet3vnet/xuexiqiangguo/raw/master/pandalearning%20(2).exe

**Comment by freessrnet3vnet** [comment]
複製代碼的時候格式錯誤，造成List就一個元素，初學者，請見諒。下面鏈接已更正
https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning%20(2).exe

**Comment by jzmswe** [comment]
> 複製代碼的時候格式錯誤，造成List就一個元素，初學者，請見諒。下面鏈接已更正
> https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning%20(2).exe

首先感谢这位热心的朋友，辛苦了，非常感谢！
楼主你测试的时候，是不是看见文章时长1/6就认为搞定了？

昨天早上熊猫的2.5版，文章时长就一直1/6循环。
现在你的这个最新版同样如此。

**Comment by G3boy** [comment]
> 複製代碼的時候格式錯誤，造成List就一個元素，初學者，請見諒。下面鏈接已更正
> https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning%20(2).exe

依旧没用，文章分还是获取不了。还不如直接更改a-log数值，已经找到一个完美解决的数值了

**Comment by lili205** [comment]
> > 複製代碼的時候格式錯誤，造成List就一個元素，初學者，請見諒。下面鏈接已更正
> > https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning%20(2).exe
> 
> 依旧没用，文章分还是获取不了。还不如直接更改a-log数值，已经找到一个完美解决的数值了

大哥你说出来啊

**Comment by hackeredsx** [comment]
大哥，你咋解决的，求指导

**Comment by hackeredsx** [comment]
> 
> 
> > > 複製代碼的時候格式錯誤，造成List就一個元素，初學者，請見諒。下面鏈接已更正
> > > https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning%20(2).exe
> > 
> > 
> > 依旧没用，文章分还是获取不了。还不如直接更改a-log数值，已经找到一个完美解决的数值了
> 
> 大哥你说出来啊



> 
> 
> 代码有问题，第8行你把关键字str赋值了，会报错
> 
> > 追踪HTTP协议后发现在json请求后有个时间戳信息，估计是用来抓刷机的，现将带时间戳的请求修改如下（还是修改get_links.py文件，暂时修改文章列表获取方法，估计不久视频列表也会发生变化）：
> > ```
> > import requests
> > import re
> > import time
> > def get_article_links():
> >     try:
> >         t_str=int(time.time()/60)
> >         url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str)
> >         str=requests.get(url)
> >         strList=str.json()
> >         links=[]
> >         for i in strList:
> >             links.append(i['url'])
> >         return links
> > 
> >     except:
> >         print("=" * 120)
> >         print("get_article_links获取失败")
> >         print("=" * 120)
> >         raise
> > ```

代码确实有问题，运行报错

**Comment by jzmswe** [comment]
我改了，也搞定了。但我不知道自己改的这个数值是否最合适，哪位朋友指点一下，最佳数值应该是多少？

**Comment by jzmswe** [comment]
> > > 複製代碼的時候格式錯誤，造成List就一個元素，初學者，請見諒。下面鏈接已更正
> > > https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning%20(2).exe
> > 
> > 
> > 依旧没用，文章分还是获取不了。还不如直接更改a-log数值，已经找到一个完美解决的数值了
> 
> 大哥你说出来啊

他已经说出来了，我也按他说的搞定了。如果能说出比较合适的数值就更好了，现在这个数值是我随便改的，不知是否最佳。

**Comment by hackeredsx** [comment]
> 
> 
> > > > 複製代碼的時候格式錯誤，造成List就一個元素，初學者，請見諒。下面鏈接已更正
> > > > https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning%20(2).exe
> > > 
> > > 
> > > 依旧没用，文章分还是获取不了。还不如直接更改a-log数值，已经找到一个完美解决的数值了
> > 
> > 
> > 大哥你说出来啊
> 
> 他已经说出来了，我也按他说的搞定了。如果能说出比较合适的数值就更好了，现在这个数值是我随便改的，不知是否最佳。

a-log具体如何改

**Comment by soikjk** [comment]
> > > > 複製代碼的時候格式錯誤，造成List就一個元素，初學者，請見諒。下面鏈接已更正
> > > > https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning%20(2).exe
> > > 
> > > 
> > > 依旧没用，文章分还是获取不了。还不如直接更改a-log数值，已经找到一个完美解决的数值了
> > 
> > 
> > 大哥你说出来啊
> 
> > 代码有问题，第8行你把关键字str赋值了，会报错
> > > 追踪HTTP协议后发现在json请求后有个时间戳信息，估计是用来抓刷机的，现将带时间戳的请求修改如下（还是修改get_links.py文件，暂时修改文章列表获取方法，估计不久视频列表也会发生变化）：
> > > ```
> > > import requests
> > > import re
> > > import time
> > > def get_article_links():
> > >     try:
> > >         t_str=int(time.time()/60)
> > >         url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str)
> > >         str=requests.get(url)
> > >         strList=str.json()
> > >         links=[]
> > >         for i in strList:
> > >             links.append(i['url'])
> > >         return links
> > > 
> > >     except:
> > >         print("=" * 120)
> > >         print("get_article_links获取失败")
> > >         print("=" * 120)
> > >         raise
> > > ```
> 
> 代码确实有问题，运行报错

还是可以的 把url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str) 
改成 s_str = "https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st="
         url = f'{s_str}{t_str}'


![image](https://user-images.githubusercontent.com/10259358/59546673-98870d80-8f64-11e9-9a01-57c12242b5d3.png)

**Comment by jackysnoopy** [comment]
> > 複製代碼的時候格式錯誤，造成List就一個元素，初學者，請見諒。下面鏈接已更正
> > https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning%20(2).exe
> 
> 首先感谢这位热心的朋友，辛苦了，非常感谢！
> 楼主你测试的时候，是不是看见文章时长1/6就认为搞定了？
> 
> 昨天早上熊猫的2.5版，文章时长就一直显示1/6，然后文章时长就一直循环。
> 现在你的这个最新版同样如此，阅读文章今天只有2分，文章时长现在只有1分。

**Comment by jackysnoopy** [comment]
鉴于有朋友说str函数系统不识别的问题 现将代码修改如下 ：
`import requests
import re
import time


def get_article_links():
    try:
        t_str=int(time.time()/60)
        s_str="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st="
        url=f'{s_str}{t_str}'
        str=requests.get(url)
        strList=str.json()
        links=[]
        for i in strList:
            links.append(i['url'])
        return links
    except:
        print("=" * 120)
        print("get_article_links获取失败")
        print("=" * 120)
        raise


def get_video_links():
    try:
        video = requests.get(            "https://www.xuexi.cn/4426aa87b0b64ac671c96379a3a8bd26/datadb086044562a57b441c24f2af1c8e101.js").content.decode(
            "utf8")
        pattern = r'https://www.xuexi.cn/[^,"]*html'
        link = re.findall(pattern, video, re.I)
        link.reverse()
        return link
    except:
        print("=" * 120)
        print("get_video_links获取失败")
        print("=" * 120)
        raise
`
视频学习的地址暂时还未发现有变动，若发现视频也有问题的话可仿照文章获取的方式重新获取视频列表。运行结果如下，确保可以用。
[https://github.com/jackysnoopy/pic/blob/master/learningpanda.png](url)

**Comment by wwdy125** [comment]
> 
> 
> 鉴于有朋友说str函数系统不识别的问题 现将代码修改如下 ：
> 
> ```
> import requests
> import re
> import time
> 
> 
> def get_article_links():
>     try:
>         t_str=int(time.time()/60)
>         s_str="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st="
>         url=f'{s_str}{t_str}'
>         str=requests.get(url)
>         strList=str.json()
>         links=[]
>         for i in strList:
>             links.append(i['url'])
>         return links
>     except:
>         print("=" * 120)
>         print("get_article_links获取失败")
>         print("=" * 120)
>         raise
> 
> 
> def get_video_links():
>     try:
>         video = requests.get("https://www.xuexi.cn/4426aa87b0b64ac671c96379a3a8bd26/datadb086044562a57b441c24f2af1c8e101.js").content.decode("utf8")
>         pattern = r'https://www.xuexi.cn/[^,"]*html'
>         link = re.findall(pattern, video, re.I)
>         link.reverse()
>         return link
>     except:
>         print("=" * 120)
>         print("get_video_links获取失败")
>         print("=" * 120)
>         raise
> ```
> 
> 视频学习的地址暂时还未发现有变动，若发现视频也有问题的话可仿照文章获取的方式重新获取视频列表。运行结果如下，确保可以用。
> ![image](https://github.com/jackysnoopy/pic/blob/master/learningpanda.png)

好人请放出程序下载

**Comment by freessrnet3vnet** [comment]
https://github.com/freessrnet3vnet/xuexiqiangguo/raw/master/pandalearning%20(3).exe
按照下面代碼編譯的可執行文件，積分不够的同學試試看。

import requests
import re
import time


def get_article_links():
    try:
        t_str=int(time.time()/60)
        s_str="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st="
        url=f'{s_str}{t_str}'
        str=requests.get(url)
        strList=str.json()
        links=[]
        for i in strList:
            links.append(i['url'])
        return links
    except:
        print("=" * 120)
        print("get_article_links获取失败")
        print("=" * 120)
        raise


def get_video_links():
    try:
        video = requests.get("https://www.xuexi.cn/4426aa87b0b64ac671c96379a3a8bd26/datadb086044562a57b441c24f2af1c8e101.js").content.decode("utf8")
        pattern = r'https://www.xuexi.cn/[^,"]*html'
        link = re.findall(pattern, video, re.I)
        link.reverse()
        return link
    except:
        print("=" * 120)
        print("get_video_links获取失败")
        print("=" * 120)
        raise

**Comment by jackysnoopy** [comment]
> > > > > 複製代碼的時候格式錯誤，造成List就一個元素，初學者，請見諒。下面鏈接已更正
> > > > > https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning%20(2).exe
> > > > 
> > > > 
> > > > 依旧没用，文章分还是获取不了。还不如直接更改a-log数值，已经找到一个完美解决的数值了
> > > 
> > > 
> > > 大哥你说出来啊
> > 
> > 
> > > 代码有问题，第8行你把关键字str赋值了，会报错
> > > > 追踪HTTP协议后发现在json请求后有个时间戳信息，估计是用来抓刷机的，现将带时间戳的请求修改如下（还是修改get_links.py文件，暂时修改文章列表获取方法，估计不久视频列表也会发生变化）：
> > > > ```
> > > > import requests
> > > > import re
> > > > import time
> > > > def get_article_links():
> > > >     try:
> > > >         t_str=int(time.time()/60)
> > > >         url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str)
> > > >         str=requests.get(url)
> > > >         strList=str.json()
> > > >         links=[]
> > > >         for i in strList:
> > > >             links.append(i['url'])
> > > >         return links
> > > > 
> > > >     except:
> > > >         print("=" * 120)
> > > >         print("get_article_links获取失败")
> > > >         print("=" * 120)
> > > >         raise
> > > > ```
> > 
> > 
> > 代码确实有问题，运行报错
> 
> 还是可以的 把url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str)
> 改成 s_str = "https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st="
> url = f'{s_str}{t_str}'
> 
> ![image](https://user-images.githubusercontent.com/10259358/59546673-98870d80-8f64-11e9-9a01-57c12242b5d3.png)



> > > > > 複製代碼的時候格式錯誤，造成List就一個元素，初學者，請見諒。下面鏈接已更正
> > > > > https://github.com/freessrnet3vnet/xuexiqiangguo/blob/master/pandalearning%20(2).exe
> > > > 
> > > > 
> > > > 依旧没用，文章分还是获取不了。还不如直接更改a-log数值，已经找到一个完美解决的数值了
> > > 
> > > 
> > > 大哥你说出来啊
> > 
> > 
> > > 代码有问题，第8行你把关键字str赋值了，会报错
> > > > 追踪HTTP协议后发现在json请求后有个时间戳信息，估计是用来抓刷机的，现将带时间戳的请求修改如下（还是修改get_links.py文件，暂时修改文章列表获取方法，估计不久视频列表也会发生变化）：
> > > > ```
> > > > import requests
> > > > import re
> > > > import time
> > > > def get_article_links():
> > > >     try:
> > > >         t_str=int(time.time()/60)
> > > >         url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str)
> > > >         str=requests.get(url)
> > > >         strList=str.json()
> > > >         links=[]
> > > >         for i in strList:
> > > >             links.append(i['url'])
> > > >         return links
> > > > 
> > > >     except:
> > > >         print("=" * 120)
> > > >         print("get_article_links获取失败")
> > > >         print("=" * 120)
> > > >         raise
> > > > ```
> > 
> > 
> > 代码确实有问题，运行报错
> 
> 还是可以的 把url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str)
> 改成 s_str = "https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st="
> url = f'{s_str}{t_str}'
> 
> ![image](https://user-images.githubusercontent.com/10259358/59546673-98870d80-8f64-11e9-9a01-57c12242b5d3.png)

**Comment by jackysnoopy** [comment]
> 代码有问题，第8行你把关键字str赋值了，会报错
> 
> > 追踪HTTP协议后发现在json请求后有个时间戳信息，估计是用来抓刷机的，现将带时间戳的请求修改如下（还是修改get_links.py文件，暂时修改文章列表获取方法，估计不久视频列表也会发生变化）：
> > ```
> > import requests
> > import re
> > import time
> > def get_article_links():
> >     try:
> >         t_str=int(time.time()/60)
> >         url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str)
> >         str=requests.get(url)
> >         strList=str.json()
> >         links=[]
> >         for i in strList:
> >             links.append(i['url'])
> >         return links
> > 
> >     except:
> >         print("=" * 120)
> >         print("get_article_links获取失败")
> >         print("=" * 120)
> >         raise
> > ```

把第八行的str和下面的str改成其他变量即可，疏忽了。
谢谢指正

**Comment by lvyu321** [comment]
> > 代码有问题，第8行你把关键字str赋值了，会报错
> > > 追踪HTTP协议后发现在json请求后有个时间戳信息，估计是用来抓刷机的，现将带时间戳的请求修改如下（还是修改get_links.py文件，暂时修改文章列表获取方法，估计不久视频列表也会发生变化）：
> > > ```
> > > import requests
> > > import re
> > > import time
> > > def get_article_links():
> > >     try:
> > >         t_str=int(time.time()/60)
> > >         url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str)
> > >         str=requests.get(url)
> > >         strList=str.json()
> > >         links=[]
> > >         for i in strList:
> > >             links.append(i['url'])
> > >         return links
> > > 
> > >     except:
> > >         print("=" * 120)
> > >         print("get_article_links获取失败")
> > >         print("=" * 120)
> > >         raise
> > > ```
> 
> 把第八行的str和下面的str改成其他变量即可，疏忽了。
> 谢谢指正

感谢大神帮忙编译，可用，谢谢。

**Comment by cybmp3** [comment]
友情提示，python3.5没f string这功能。。要切换python3.6+
debian9默认是python3.5

**Comment by adslhuang** [comment]
谢谢，可用，但无法打包成为exe，奇怪。
Pyinstaller使用f参数，然后就卡住不走了，不使用参数，打包的程序也是闪退。
会是什么原因呢？？

**Comment by asdqwe111** [comment]
> https://github.com/freessrnet3vnet/xuexiqiangguo/raw/master/pandalearning%20(3).exe
> 按照下面代碼編譯的可執行文件，積分不够的同學試試看。
> 
> import requests
> import re
> import time
> 
> def get_article_links():
> try:
> t_str=int(time.time()/60)
> s_str="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st="
> url=f'{s_str}{t_str}'
> str=requests.get(url)
> strList=str.json()
> links=[]
> for i in strList:
> links.append(i['url'])
> return links
> except:
> print("=" * 120)
> print("get_article_links获取失败")
> print("=" * 120)
> raise
> 
> def get_video_links():
> try:
> video = requests.get("[https://www.xuexi.cn/4426aa87b0b64ac671c96379a3a8bd26/datadb086044562a57b441c24f2af1c8e101.js").content.decode("utf8](https://www.xuexi.cn/4426aa87b0b64ac671c96379a3a8bd26/datadb086044562a57b441c24f2af1c8e101.js%22).content.decode(%22utf8)")
> pattern = r'[https://www.xuexi.cn/[^,"]*html](https://www.xuexi.cn/%5B%5E,%22%5D*html)'
> link = re.findall(pattern, video, re.I)
> link.reverse()
> return link
> except:
> print("=" * 120)
> print("get_video_links获取失败")
> print("=" * 120)
> raise

这段代码我替换进去，依然报错。。。。你确定可以？

**Comment by adslhuang** [comment]
确定可以，遇到问题解决问题就可以了
我遇到报错，在每个文件的开头添加
# coding=gbk
就可以了 
有其他的报错是因为安装的环境缺少包，需要安装支持的包。
如果懂编程可以试一试，如果不懂估计弄不出来。
我现在已经可以正常运行，但不能打包成exe。我也懒得找原因了，能用就行。

**Comment by adslhuang** [comment]
python环境需要安装下面的模块，才能让这个程序正常使用。也就是我上面说的包。

执行下面命令安装模块
C:\Users\h\AppData\Local\Programs\Python\Python37\Scripts>
pip install requests
pip install selenium

**Comment by adslhuang** [comment]
> a-log

这个参数是起什么作用的，谁知道吗？？

**Comment by jzmswe** [comment]
> > a-log
> 
> 这个参数是起什么作用的，谁知道吗？？

这是文件名，这个文件的里面才是参数。

**Comment by adslhuang** [comment]
> > > a-log
> > 
> > 
> > 这个参数是起什么作用的，谁知道吗？？
> 
> 这是文件名，这个文件的里面才是参数。

不要说废话，这里面的是干什么的。

**Comment by Shiyna** [comment]
感谢组织感谢dang，已正常！请问下文章列表和视频文章列表是怎么抓包分析获取到的呢？

**Comment by chegreat** [comment]
> 谢谢，可用，但无法打包成为exe，奇怪。
> Pyinstaller使用f参数，然后就卡住不走了，不使用参数，打包的程序也是闪退。
> 会是什么原因呢？？

我使用python pyinstaller.py -F -c 参数打包可以成功，使用python pyinstaller.py -w -F打包的文件就是闪退。

**Comment by ZhaoqiangCn** [comment]
> > 代码有问题，第8行你把关键字str赋值了，会报错
> > > 追踪HTTP协议后发现在json请求后有个时间戳信息，估计是用来抓刷机的，现将带时间戳的请求修改如下（还是修改get_links.py文件，暂时修改文章列表获取方法，估计不久视频列表也会发生变化）：
> > > ```
> > > import requests
> > > import re
> > > import time
> > > def get_article_links():
> > >     try:
> > >         t_str=int(time.time()/60)
> > >         url="https://www.xuexi.cn/lgdata/u1ght1omn2.json?_st=" + str(t_str)
> > >         str=requests.get(url)
> > >         strList=str.json()
> > >         links=[]
> > >         for i in strList:
> > >             links.append(i['url'])
> > >         return links
> > > 
> > >     except:
> > >         print("=" * 120)
> > >         print("get_article_links获取失败")
> > >         print("=" * 120)
> > >         raise
> > > ```
> 
> 把第八行的str和下面的str改成其他变量即可，疏忽了。
> 谢谢指正

感谢，可用谢谢

**Comment by like-yeer** [comment]
https://github.com/freessrnet3vnet/xuexiqiangguo/raw/master/pandalearning%20(3).exe可用，谢谢

**Comment by mithrawrx** [comment]
非常感谢各位老师的帮助

**Comment by ZRONIN** [comment]
Exception in thread 文章学习:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "F:\ProgramStudy\python\19xxqg\pdlearn\threads.py", line 23, in run
    self.func(*self.args)
  File "F:/ProgramStudy/python/19xxqg/pandalearning.py", line 59, in article
    driver_article.set_cookies(cookies)
  File "F:\ProgramStudy\python\19xxqg\pdlearn\mydriver.py", line 116, in set_cookies
    self.driver.add_cookie({k: cookie[k] for k in cookie.keys()})
  File "D:\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 894, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "D:\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid 'expiry'
  (Session info: headless chrome=75.0.3770.100)
求错误解决方法

**Comment by jackysnoopy** [comment]
> Exception in thread 文章学习:
> Traceback (most recent call last):
> File "D:\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
> self.run()
> File "F:\ProgramStudy\python\19xxqg\pdlearn\threads.py", line 23, in run
> self.func(*self.args)
> File "F:/ProgramStudy/python/19xxqg/pandalearning.py", line 59, in article
> driver_article.set_cookies(cookies)
> File "F:\ProgramStudy\python\19xxqg\pdlearn\mydriver.py", line 116, in set_cookies
> self.driver.add_cookie({k: cookie[k] for k in cookie.keys()})
> File "D:\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 894, in add_cookie
> self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
> File "D:\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "D:\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid 'expiry'
> (Session info: headless chrome=75.0.3770.100)
> 求错误解决方法

将chome的版本降到73

**Comment by xuxudong1110** [comment]
现在为什么爬不到文章列表了

**Comment by lvyu321** [comment]
今天上午阅读文章的列表估计更新了，现在能够完成阅读文章时长的任务，但是阅读文章的数量没有发生变化。
