### ISSUE TITLE
输入账号密码提示mydriver初始化失败

### ISSUE THREAD

**Issue by tiger1890** [Alivon/Panda-Learning#408]
手机安装的。。 -

**Comment by jiangchen1020** [comment]
mac
报错。Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "selenium/webdriver/common/service.py", line 76, in start
  File "subprocess.py", line 729, in __init__
  File "subprocess.py", line 1364, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn/dingding.py", line 23, in dd_login_status
  File "pdlearn/mydriver.py", line 47, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 73, in __init__
  File "selenium/webdriver/common/service.py", line 83, in start
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

[546] Failed to execute script pandalearning

**Comment by xiakangwei** [comment]
我也是这个情况
