### ISSUE TITLE
手机端输入密码后出错，请看看

### ISSUE THREAD

**Issue by tiger1890** [Alivon/Panda-Learning#410]
========
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "pandalearning.py", line 21, in user_flag
    cookies = dingding.dd_login_status(uname)
  File "/root/pdlearn/dingding.py", line 23, in dd_login_status
    driver_login = mydriver.Mydriver(noimg=False)
  File "/root/pdlearn/mydriver.py", line 47, in __init__
    self.driver = self.webdriver.Chrome(chrome_options=self.options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

root@localhost:~#

**Comment by tiger1890** [comment]
是否要下载chromedriver

**Comment by tiger1890** [comment]
已经成功，现在请问怎么改单线程。。在哪输命令啊

**Comment by shenlongba** [comment]
> 已经成功，现在请问怎么改单线程。。在哪输命令啊

请问下，手机端怎么下载？谢谢了。

**Comment by yxqgly** [comment]
是怎么解决的？我都重下好几次了，还是没解决
