### ISSUE TITLE
Mydriver 初始化失败 -Message: 'chromedriver.exe' executable may have wrong permissions

### ISSUE THREAD

**Issue by AnnaWithKKK** [Alivon/Panda-Learning#414]
之前在windows直接用编译好的熊猫，很好用。现在不是文章没法读取了么。。。 参考大家的修改方法，重新在ubuntu18.04下修改 get_links.py 后用 `python pandalearning.py`运行源代码，出现“Mydriver初始化失败”。
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './chrome/chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "pandalearning.py", line 18, in user_flag
    driver_login = mydriver.Mydriver(nohead=False)
  File "/home/kevin/Downloads/Panda-Learning/Source Packages/pdlearn/mydriver.py", line 36, in __init__
    chrome_options=self.options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
`
请问各位怎么解决啊。。。  多谢了。。。。

**Comment by AnnaWithKKK** [comment]
补充下，貌似最开始ubuntu下我系统上运行panda就出现这样的问题，和系统配置有关，和修改get_links.py 无关。

**Comment by jackysnoopy** [comment]
PermissionError: [Errno 13] Permission denied: './chrome/chromedriver.exe' 你用的chome驱动是windows下的驱动，在ubuntu18.04下编译肯定出问题

**Comment by AnnaWithKKK** [comment]
。。。 晕菜！ 豁然开朗！感谢 @jackysnoopy
