### ISSUE TITLE
  各位大佬  提示无效的参数 expiry   Message: invalid argument: invalid 'expiry'  这是怎么办~

### ISSUE THREAD

**Issue by dyf1989314** [Alivon/Panda-Learning#423]
开启： 文章学习
开启： 视频学习
Exception in thread 文章学习:

selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid 'expiry'
  (Session info: headless chrome=75.0.3770.100)

Exception in thread 视频学习:

selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid 'expiry'
  (Session info: headless chrome=75.0.3770.100)

各位大佬  提示无效的参数 expiry   这是怎么办    ~~~

**Comment by dyf1989314** [comment]
当前学习总积分：276
阅读文章:0/6,观看视频:1/6,登陆:1/1,文章时长:0/6,视频时长:2/6
开启： 文章学习
开启： 视频学习
Exception in thread 文章学习:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/pdlearn/threads.py", line 23, in run
    self.func(*self.args)
  File "pandalearning.py", line 59, in article
    driver_article.set_cookies(cookies)
  File "/root/pdlearn/mydriver.py", line 116, in set_cookies
    self.driver.add_cookie({k: cookie[k] for k in cookie.keys()})
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 894, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid 'expiry'
  (Session info: headless chrome=75.0.3770.100)


Exception in thread 视频学习:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/pdlearn/threads.py", line 23, in run
    self.func(*self.args)
  File "pandalearning.py", line 118, in video
    driver_video.set_cookies(cookies)
  File "/root/pdlearn/mydriver.py", line 116, in set_cookies
    self.driver.add_cookie({k: cookie[k] for k in cookie.keys()})
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 894, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid 'expiry'
  (Session info: headless chrome=75.0.3770.100)

**Comment by ZRONIN** [comment]
回退chromederive到对应版本

**Comment by ZRONIN** [comment]
或者使用程序自带的chrome程序

**Comment by jackysnoopy** [comment]
chome版本过高，使用73以下的版本
