### ISSUE TITLE
mac不支持最新的chrome浏览器了，下载不到70-73版本的chrome怎么办？

### ISSUE THREAD

**Issue by noinlijin** [Alivon/Panda-Learning#431]
```

Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn/dingding.py", line 23, in dd_login_status
  File "pdlearn/mydriver.py", line 39, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 81, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 157, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 252, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.15.0 x86_64)

[63936] Failed to execute script pandalearning

```

**Comment by lxq73061** [comment]
我也是同样问题

MacBook-Pro:pandalearning_macos steven$ ./pandalearning user1
开启： 获取更新信息...

正在联网获取更新信息...
是否保存钉钉帐户密码，保存后可后免登陆学习(Y/N) 熊猫学习唯一下载地址为 https://github.com/Alivon/Panda-Learning
程序版本为：v2.5，
最新版本为：v2.5
========================================================================================================================
========================================================================================================================
更新显示不会打断之前输入等操作，请继续......（若已输入用户标记直接enter）

========================================================================================================================
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 18, in user_flag
  File "pdlearn/mydriver.py", line 39, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 81, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 157, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 252, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.14.1 x86_64)

[1154] Failed to execute script pandalearning
MacBook-Pro:pandalearning_macos steven$

**Comment by cmjdxy** [comment]
Check [this](https://chromedriver.storage.googleapis.com/index.html?path=2.46/)

**Comment by muchao** [comment]
我也这样，后来自己去google下了新版本的chromedriver就好了
