### ISSUE TITLE
是不是挂掉了？

### ISSUE THREAD

**Issue by longmoonwork** [Alivon/Panda-Learning#433]
报错
更新显示不会打断之前输入等操作，请继续......（若已输入用户标记直接enter）
登陆中...
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "pandalearning.py", line 15, in user_flag
    cookies = dingding.dd_login_status(uname, has_dd=True)
  File "/root/pdlearn/dingding.py", line 27, in dd_login_status
    cookies = driver_login.get_cookies()
  File "/root/pdlearn/mydriver.py", line 111, in get_cookies
    cookies = self.driver.get_cookies()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 841, in get_cookies
    return self.execute(Command.GET_ALL_COOKIES)['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid session id
  (Driver info: chromedriver=72.0.3626.7 (efcef9a3ecda02b2132af215116a03852d08b9cb),platform=Linux 5.0.16-300.fc30.x86_64 x86_64)

大佬们都这样吗？  我这个是在Fedora上运行的~

**Comment by danjuanyang** [comment]
我的好像也挂了

**Comment by MCSeekeri** [comment]
看起来是的，你是什么系统？



发自我的小米手机
在 longmoonwork <notifications@github.com>，2019年7月10日 上午9:45写道：

报错
更新显示不会打断之前输入等操作，请继续......（若已输入用户标记直接enter）
登陆中...
Traceback (most recent call last):
File "pandalearning.py", line 180, in
cookies, a_log, v_log = user_flag(dd_status, uname)
File "pandalearning.py", line 15, in user_flag
cookies = dingding.dd_login_status(uname, has_dd=True)
File "/root/pdlearn/dingding.py", line 27, in dd_login_status
cookies = driver_login.get_cookies()
File "/root/pdlearn/mydriver.py", line 111, in get_cookies
cookies = self.driver.get_cookies()
File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 841, in get_cookies
return self.execute(Command.GET_ALL_COOKIES)['value']
File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid session id
(Driver info: chromedriver=72.0.3626.7 (efcef9a3ecda02b2132af215116a03852d08b9cb),platform=Linux 5.0.16-300.fc30.x86_64 x86_64)

大佬们都这样吗？ 我这个是在Fedora上运行的~

**Comment by MCSeekeri** [comment]
我用Termux啥事没有，依然能用



在 danjuanyang <notifications@github.com>，2019年7月10日 上午11:07写道：

我的好像也挂了

**Comment by gantrylueng** [comment]
能不能用已经不重要了。重要的是用了这个会被识别出来，封禁你的账号。
所以就没有必要用了。

**Comment by Alivon** [comment]
我自用还一切正常哈，无法确定阿里识别方法，但是我现在已经没有时间更新了，大家看情况用吧

**Comment by danjuanyang** [comment]
> 我自用还一切正常哈，无法确定阿里识别方法，但是我现在已经没有时间更新了，大家看情况用吧

又ok了，可以用了，之前可能是个别小状况

**Comment by sunzp21** [comment]
视频不能学习了

**Comment by tantaiheng** [comment]
get_video_links获取失败
那位大佬能提供一下最新的视频地址，应该是之前的地址不能用了

**Comment by huangsiyuan924** [comment]
> 我自用还一切正常哈，无法确定阿里识别方法，但是我现在已经没有时间更新了，大家看情况用吧

昨天是钉钉登录账户密码加了个验证码.,导致无法账户密码登录,mydriver加几行 截图当前屏幕,让用户自己输入验证码.或者用识别验证码api,sendkeys到input标签,click就可以了......二维码登录还没事

**Comment by lwjmzla** [comment]
> > 我自用还一切正常哈，无法确定阿里识别方法，但是我现在已经没有时间更新了，大家看情况用吧
> 
> 昨天是钉钉登录账户密码加了个验证码.,导致无法账户密码登录,mydriver加几行 截图当前屏幕,让用户自己输入验证码.或者用识别验证码api,sendkeys到input标签,click就可以了......二维码登录还没事

能用么，要怎么弄？
