### ISSUE TITLE
无法使用了？

### ISSUE THREAD

**Issue by manghs** [Alivon/Panda-Learning#438]
Traceback (most recent call last):
  File "pandalearning.py", line 181, in <module>
  File "pandalearning.py", line 49, in show_score
  File "pdlearn\score.py", line 12, in get_score
TypeError: 'NoneType' object is not subscriptable
[7516] Failed to execute script pandalearning
请按任意键继续. . .

**Comment by 87051392** [comment]
用二维码登录还可以用

**Comment by manghs** [comment]
楼上的大神，还有其他办法了吗？？二维码很麻烦啊

**Comment by longmoonwork** [comment]
没有图形界面  挂在VPS上的 没法二维码登陆啊~
