### ISSUE TITLE
最新问题修复

### ISSUE THREAD

**Issue by menghuanzhixiang** [Alivon/Panda-Learning#445]
修复方法参考issue #440  感谢！
把验证码等待时间减少为30S
然后打包成exe
下面是下载地址
https://drive.google.com/open?id=1Lmlit-WtopB5ZxJMOH7KMTx0dlifSig4

**Comment by gqyun88** [comment]
按这个是不是每次都要手动输入验证码，那岂不是后面加的参数失去意义啦

**Comment by menghuanzhixiang** [comment]
> 按这个是不是每次都要手动输入验证码，那岂不是后面加的参数失去意义啦

验证码没法跳过的  后面的参数也有用

**Comment by luyan29** [comment]
实测登录进去可用，感谢！！

**Comment by lili205** [comment]
谢谢，跪拜大佬。给大佬递茶。

**Comment by menghuanzhixiang** [comment]
输入完验证码别关闭浏览器，登陆成功后会自动隐藏

**Comment by jzmswe** [comment]
多谢楼主，以前的问题包括进去了吗？
https://github.com/Alivon/Panda-Learning/issues/403

**Comment by 87051392** [comment]
大佬，能打包个mac能用的吗？不会编译源代码啊。

**Comment by menghuanzhixiang** [comment]
> 多谢楼主，以前的问题，解决方法包括进去了吗？
> #403
文章没有问题，官网又改回来了

**Comment by menghuanzhixiang** [comment]
> 大佬，能打包个mac能用的吗？不会编译源代码啊。

不是大佬，现学现卖的，mac不会

**Comment by squirrelmedia** [comment]
跪谢大佬的打包，就是有验证码之后麻烦了很多

**Comment by FLASH023** [comment]
钉钉验证码有bug
可以绕过  

这里不便明说  否则很快会被堵上

**Comment by xinbokong** [comment]
大师们，怎么绕开钉钉的验证码呀？

**Comment by menghuanzhixiang** [comment]
> 下载地址进不去啊

需要梯子

**Comment by Joffgithub1997** [comment]
谢谢大佬

**Comment by gqyun88** [comment]
linux设成自动运行的完蛋了

**Comment by jackysnoopy** [comment]
现在设置计划任务的无法使用了，估计得加入图像识别技术才可自动填写验证码，感觉这个就是个提高技术的过程。

**Comment by icman02200459** [comment]
这个包下载以后提示计算机丢失api-ms-win-crt-process--1-1-0.dll 尝试重新安装解决问题，原来的执行程序没有这个问题，可以提示一下问题出在哪里么？？

**Comment by jackysnoopy** [comment]
需要下载什么包？直接执行源码不就可以了。

**Comment by hackeredsx** [comment]
求发一下新的exe，本人不能翻墙

**Comment by menghuanzhixiang** [comment]
> 求发一下新的exe，本人不能翻墙

国内网盘不敢用

**Comment by xinbokong** [comment]
新的exe，我的百度网盘可以下载。链接:https://pan.baidu.com/s/1JX97_8gfmgLcxTizzMSxXg 提取码:y29k

**Comment by long201900** [comment]
![image](https://user-images.githubusercontent.com/51848624/61297693-4cebac00-a80f-11e9-93ab-95f50b4d49fb.png)

**Comment by long201900** [comment]
就不动了！什么情况啊！大神们

**Comment by lofter414** [comment]
linux怎么破？这种思路可以吗？

**Comment by menghuanzhixiang** [comment]
> linux怎么破？这种思路可以吗？

linux直接看440的解决方法  直接运行py

**Comment by lofter414** [comment]
> > linux怎么破？这种思路可以吗？
> 
> linux直接看440的解决方法 直接运行py

> > linux怎么破？这种思路可以吗？
> 
> linux直接看440的解决方法 直接运行py

依旧有报错如下：
```
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "/root/xuexiqiangguo/pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "/root/xuexiqiangguo/pandalearning.py", line 15, in user_flag
    cookies = dingding.dd_login_status(uname, has_dd=True)
  File "/root/xuexiqiangguo/pdlearn/dingding.py", line 23, in dd_login_status
    driver_login = mydriver.Mydriver(noimg=False,nohead=False)
  File "/root/xuexiqiangguo/pdlearn/mydriver.py", line 54, in __init__
    self.driver = self.webdriver.Chrome(chrome_options=self.options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=72.0.3626.7 (efcef9a3ecda02b2132af215116a03852d08b9cb),platform=Linux 3.10.0-957.10.1.el7.x86_64 x86_64)
```

**Comment by EstelleC1104** [comment]
登陆中...
请输入正确的图片验证码
读取用户信息成功

DevTools listening on ws://127.0.0.1:57173/devtools/browser/d7a9945c-0973-4821-94d9-9ab094d6ea36
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 15, in user_flag
  File "pdlearn\dingding.py", line 24, in dd_login_status
  File "pdlearn\mydriver.py", line 95, in dd_login
  File "site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
  File "site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17763 x86_64)

[5876] Failed to execute script pandalearning

**Comment by cabnine** [comment]
win10下倒是可以用，win7为啥闪退？不兼容？

**Comment by EstelleC1104** [comment]
我的就是win10呀

 
------------------
陈亦欣
Tel：18824163525
E-mail：524697332@qq.com




 




------------------ 原始邮件 ------------------
发件人: "cabnine"<notifications@github.com>; 
发送时间: 2019年7月22日(星期一) 上午9:56
收件人: "Alivon/Panda-Learning"<Panda-Learning@noreply.github.com>; 
抄送: "EstelleC"<estellec1104@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Alivon/Panda-Learning] 最新问题修复 (#445)




win10下倒是可以用，win7为啥闪退？不兼容？

**Comment by EstelleC1104** [comment]
我的就是win10呀

 


今天的：


开启： 获取更新信息...


正在联网获取更新信息...
输入用户标记名：
读取用户信息成功
熊猫学习唯一下载地址为 https://github.com/Alivon/Panda-Learning
程序版本为：v2.5，
最新版本为：v2.5
========================================================================================================================
========================================================================================================================
更新显示不会打断之前输入等操作，请继续......（若已输入用户标记直接enter）


DevTools listening on ws://127.0.0.1:53475/devtools/browser/0e9f6ccb-4da4-4742-a608-8b89cf1ca63a
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 15, in user_flag
  File "pdlearn\dingding.py", line 24, in dd_login_status
  File "pdlearn\mydriver.py", line 95, in dd_login
  File "site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
  File "site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17763 x86_64)


[10808] Failed to execute script pandalearning













------------------ 原始邮件 ------------------
发件人: "cabnine"<notifications@github.com>; 
发送时间: 2019年7月22日(星期一) 上午9:56
收件人: "Alivon/Panda-Learning"<Panda-Learning@noreply.github.com>; 
抄送: "EstelleC"<estellec1104@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Alivon/Panda-Learning] 最新问题修复 (#445)




win10下倒是可以用，win7为啥闪退？不兼容？

**Comment by EstelleC1104** [comment]
我的就是win10呀

 


今天的：


开启： 获取更新信息...


正在联网获取更新信息...
输入用户标记名：
读取用户信息成功
熊猫学习唯一下载地址为 https://github.com/Alivon/Panda-Learning
程序版本为：v2.5，
最新版本为：v2.5
========================================================================================================================
========================================================================================================================
更新显示不会打断之前输入等操作，请继续......（若已输入用户标记直接enter）


DevTools listening on ws://127.0.0.1:53475/devtools/browser/0e9f6ccb-4da4-4742-a608-8b89cf1ca63a
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 15, in user_flag
  File "pdlearn\dingding.py", line 24, in dd_login_status
  File "pdlearn\mydriver.py", line 95, in dd_login
  File "site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
  File "site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17763 x86_64)


[10808] Failed to execute script pandalearning








下午的：


========================================================================================================================
更新显示不会打断之前输入等操作，请继续......（若已输入用户标记直接enter）
登陆中...
请输入正确的图片验证码
读取用户信息成功


DevTools listening on ws://127.0.0.1:49271/devtools/browser/d1dc6a3e-70e4-4598-9b7f-8acdba6fc345
登陆中...
请输入正确的图片验证码
读取用户信息成功


DevTools listening on ws://127.0.0.1:49319/devtools/browser/a7ef5c06-8009-43fd-bd96-fe39cd6a4066
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 15, in user_flag
  File "pdlearn\dingding.py", line 24, in dd_login_status
  File "pdlearn\mydriver.py", line 95, in dd_login
  File "site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
  File "site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17763 x86_64)


[8940] Failed to execute script pandalearning












------------------ 原始邮件 ------------------
发件人: "cabnine"<notifications@github.com>; 
发送时间: 2019年7月22日(星期一) 上午9:56
收件人: "Alivon/Panda-Learning"<Panda-Learning@noreply.github.com>; 
抄送: "EstelleC"<estellec1104@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Alivon/Panda-Learning] 最新问题修复 (#445)




win10下倒是可以用，win7为啥闪退？不兼容？

**Comment by manghs** [comment]
楼主下载地址失效，打不开，麻烦再给个谢谢

**Comment by xinbokong** [comment]
------------------ 原始邮件 ------------------
发件人: "manghs"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 晚上10:42
收件人: "Alivon/Panda-Learning"<Panda-Learning@noreply.github.com>;
抄送: "~孔~"<1151597693@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Alivon/Panda-Learning] 最新问题修复 (#445)




楼主下载地址失效，打不开，麻烦再给个谢谢

**Comment by xinbokong** [comment]
链接：https://pan.baidu.com/s/1gmRs-nJQdQc4SXTZs70jIQ 
提取码：mkye 







------------------ 原始邮件 ------------------
发件人: "manghs"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 晚上10:42
收件人: "Alivon/Panda-Learning"<Panda-Learning@noreply.github.com>;
抄送: "~孔~"<1151597693@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Alivon/Panda-Learning] 最新问题修复 (#445)




楼主下载地址失效，打不开，麻烦再给个谢谢
