### ISSUE TITLE
直接运行源码,get_video_links获取失败

### ISSUE THREAD

**Issue by MQL9011** [Alivon/Panda-Learning#453]
环境是Python3
我直接在Unbuntu服务器上跑的源码.

之前一直好好的. 这几天突然都报错了. 貌似是获取积分方式里头的数据格式变了?
```
get_video_links获取失败
========================================================================================================================
Traceback (most recent call last):
  File "pandalearning.py", line 181, in <module>
    total, each = show_score(cookies)
  File "pandalearning.py", line 49, in show_score
    total, each = score.get_score(cookies)
  File "/home/mccree/Desktop/Learn/pdlearn/score.py", line 12, in get_score
    total = int(json.loads(total, encoding="utf8")["data"]["score"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by hellomelody** [comment]
+1

**Comment by muchao** [comment]
+1

**Comment by sunzp21** [comment]
请问解决了吗？
