### ISSUE TITLE
8月15日无法登录，求解

### ISSUE THREAD

**Issue by lwjmzla** [Alivon/Panda-Learning#468]
DevTools listening on ws://127.0.0.1:65029/devtools/browser/fc934f9c-2047-4890-a05c-ef8e1086544f
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 15, in user_flag
  File "pdlearn\dingding.py", line 24, in dd_login_status
  File "pdlearn\mydriver.py", line 95, in dd_login
IndexError: list index out of range
[5744] Failed to execute script pandalearning

**Comment by shineachen** [comment]
我也是登不上了

**Comment by HOUDONGSONG** [comment]
同登录不上 又被封了？

**Comment by goldenhairlady** [comment]
网页源码更新了！！！等新的吧！



---原始邮件---
发件人: "油淋茄子"<notifications@github.com>
发送时间: 2019年8月15日(星期四) 上午10:56
收件人: "Alivon/Panda-Learning"<Panda-Learning@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Alivon/Panda-Learning] 8月15日无法登录，求解 (#468)



我也是登不上了

**Comment by newmean** [comment]
将mydirver.py中
self.driver.find_elements_by_id("mobilePlaceholder")[0].click()
修改为self.driver.find_element_by_id("mobile").click()
self.driver.find_elements_by_id("mobilePlaceholder")[1].click()
修改为self.driver.find_element_by_id("pwd").click()

就可以继续使用了

**Comment by xinbokong** [comment]
> 将mydirver.py中
> self.driver.find_elements_by_id("mobilePlaceholder")[0].click()
> 修改为self.driver.find_element_by_id("mobile").click()
> self.driver.find_elements_by_id("mobilePlaceholder")[1].click()
> 修改为self.driver.find_element_by_id("pwd").click()
> 
> 就可以继续使用了

索引越界了

**Comment by xinbokong** [comment]
list index out of range    
     索引越界了

**Comment by hnxuan** [comment]
> 将mydirver.py中
> self.driver.find_elements_by_id("mobilePlaceholder")[0].click()
> 修改为self.driver.find_element_by_id("mobile").click()
> self.driver.find_elements_by_id("mobilePlaceholder")[1].click()
> 修改为self.driver.find_element_by_id("pwd").click()
> 
> 就可以继续使用了

有打包好的程序吗

**Comment by hemudu** [comment]
求高人帮忙打包编译，谢谢啊

**Comment by hnxuan** [comment]
> 求高人帮忙打包编译，谢谢啊

链接: https://pan.baidu.com/s/1yeDxcBft0GlSnGlmf45LIw 提取码: k4dn

**Comment by hemudu** [comment]
> > 求高人帮忙打包编译，谢谢啊
> 
> 链接: https://pan.baidu.com/s/1yeDxcBft0GlSnGlmf45LIw 提取码: k4dn

非常感谢！

**Comment by hemudu** [comment]
> > 求高人帮忙打包编译，谢谢啊
> 
> 链接: https://pan.baidu.com/s/1yeDxcBft0GlSnGlmf45LIw 提取码: k4dn

<img width="744" alt="微信图片_20190816135506" src="https://user-images.githubusercontent.com/25216587/63146432-82adcb80-c02d-11e9-9321-39156cd77a6e.png">
我测试时候仍然报错，没有弹出验证码窗口，求指导解惑，谢谢

**Comment by 1090987386** [comment]
> > 求高人帮忙打包编译，谢谢啊
> 
> 链接: https://pan.baidu.com/s/1yeDxcBft0GlSnGlmf45LIw 提取码: k4dn

这个链接没法下载，请大神重新弄个分享，谢谢

**Comment by lwjmzla** [comment]
> > 求高人帮忙打包编译，谢谢啊
> 
> 链接: https://pan.baidu.com/s/1yeDxcBft0GlSnGlmf45LIw 提取码: k4dn

亲测可以执行，但是登录时等待时间久一些，操作步骤：
正常登录后，一会儿 会我的PS软件自动打开了验证码图片，自己记住验证码，关闭PS，软件会提示：请输入验证码，输入后，等待一段时间就好了。。

**Comment by 1090987386** [comment]
不知道怎么回事，我用百度云盘下载不了！请你打包这个程序，然后分享个交接吧，谢谢！！！




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: lwjmzla <notifications@github.com>
发送时间: 2019年8月17日 10:53
收件人: Alivon/Panda-Learning <Panda-Learning@noreply.github.com>
抄送: 1090987386 <1090987386@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[Alivon/Panda-Learning] 8月15日无法登录，求解 (#468)



  
求高人帮忙打包编译，谢谢啊
  
链接: https://pan.baidu.com/s/1yeDxcBft0GlSnGlmf45LIw 提取码: k4dn
  
亲测可以执行，但是登录时等待时间久一些，操作步骤：
 正常登录后，一会儿 会我的PS软件自动打开了验证码图片，自己记住验证码，关闭PS，软件会提示：请输入验证码，输入后，等待一段时间就好了。。

**Comment by lomo5** [comment]
> > > 求高人帮忙打包编译，谢谢啊
> > 
> > 
> > 链接: https://pan.baidu.com/s/1yeDxcBft0GlSnGlmf45LIw 提取码: k4dn
> 
> 亲测可以执行，但是登录时等待时间久一些，操作步骤：
> 正常登录后，一会儿 会我的PS软件自动打开了验证码图片，自己记住验证码，关闭PS，软件会提示：请输入验证码，输入后，等待一段时间就好了。。

怎么打开的验证码图片？PS软件是啥？

**Comment by chevyqq** [comment]
[0822/104130.728:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.
========================================================================================================================
get_video_links获取失败
========================================================================================================================
Traceback (most recent call last):
  File "pandalearning.py", line 183, in <module>
  File "pandalearning.py", line 49, in show_score
  File "pdlearn\score.py", line 12, in get_score
TypeError: 'NoneType' object is not subscriptable
[21028] Failed to execute script pandalearning

**Comment by xinbokong** [comment]
> > 求高人帮忙打包编译，谢谢啊
> 
> 链接: https://pan.baidu.com/s/1yeDxcBft0GlSnGlmf45LIw 提取码: k4dn

大师   能把源码发给我么？  邮箱：1151597693@qq.com

**Comment by thompson1966** [comment]
mydriver.py 文件中
第95行         
`self.driver.find_elements_by_id("mobilePlaceholder")[0].click()`
修改为
`self.driver.find_elements_by_id("mobile_content")[0].click()`
第97行
 ` self.driver.find_elements_by_id("mobilePlaceholder")[1].click()`
修改为：
`self.driver.find_elements_by_id("mobile_content")[1].click()`
就可以登录了
