### ISSUE TITLE
完美版自动学习(带验证码自动识别)

### ISSUE THREAD

**Issue by newmean** [Alivon/Panda-Learning#469]
请先在https://www.showapi.com/注册一个账号
然后在https://www.showapi.com/apiGateway/view?apiCode=184
花0.1元人民币购买100易豆,就有200次使用.(按照一个账号每天一次,你可以使用6个月以上.如果使用完了之后你可以重新注册账号然后再花0.1元购买)
然后在,个人中心-我的应用 里面查看APPID和密钥
并填写在User/Key.ini 文件里即可使用 第一个参数是APPID,第二个参数是密钥

链接: https://pan.baidu.com/s/1dW_oLB2m4KXYdiwcCGVCwg
提取码: wyjj

**Comment by hiim88** [comment]
测试了，完美识别验证码，谢谢楼主。

**Comment by zhouqie123** [comment]
提示get获取失败、、

**Comment by newmean** [comment]
> 提示get获取失败、、

请检查是否配置了接口即 /User/Key.ini 文件

**Comment by wital** [comment]
完美，谢谢楼主！

**Comment by massger** [comment]
百度网盘链接失效

**Comment by massger** [comment]
楼主能给我发一份自动识别验证码的吗？那个百度网盘的链接失效了，我的邮箱是2470313336@qq.com，感谢

**Comment by newmean** [comment]
> 楼主能给我发一份自动识别验证码的吗？那个百度网盘的链接失效了，我的邮箱是[2470313336@qq.com](mailto:2470313336@qq.com)，感谢

链接: https://pan.baidu.com/s/11e-iHJ4Xam1AqPAAlA9dKA 提取码: 8wg8

**Comment by massger** [comment]
收到，谢谢老哥

Neeao <notifications@github.com> 于2019年8月30日周五 上午1:00写道：

**Comment by seven-out** [comment]
a=ice-ufrag:nEax
a=ice-pwd:NtYnfaZ99P+axRJtx5bOSegy
a=ice-options:trickle
a=fingerprint:sha-256 71:36:1D:16:5A:6A:1D:3D:37:C0:A5:BD:86:A1:13:AB:2F:3A:80:7A:D2:61:7F:19:5E:00:4F:23:BC:43:B5:CC
a=setup:actpass
a=mid:0
a=sendrecv
a=msid:
a=rtcp-mux
a=rtpmap:119 google-data/90000
a=ssrc:751334933 cname:ibjpJuBS9841Hl7n
a=ssrc:751334933 msid:-
a=ssrc:751334933 mslabel:-
a=ssrc:751334933 label:

[0830/151012.800:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.
开始获取验证码地址
下载验证码! https://pin.aliyun.com/get_img?sessionid=k0143vyNSQo4c5GwrR7kN/WXSwQh6Xep67w5bvQz8uvQc=&identity=login.dingtalk.com&type=default
Traceback (most recent call last):
  File "xxqg.py", line 180, in <module>
  File "xxqg.py", line 15, in user_flag
  File "pdlearn\dingding.py", line 25, in dd_login_status
  File "pdlearn\mydriver.py", line 116, in dd_login
  File "pdlearn\mydriver.py", line 152, in send_captcha_chaojiyin
  File "pdlearn\mydriver.py", line 180, in get_key_captcha
ValueError: not enough values to unpack (expected 2, got 1)
[11092] Failed to execute script xxqg




[兄弟这个怎么破
![QQ截图20190830151310](https://user-images.githubusercontent.com/40521415/64000662-c5e16180-cb38-11e9-8fc5-fbdb3d5682d8.png)

**Comment by newmean** [comment]
格式错误------------------ 原始邮件 ------------------
发件人: "seven-out"<notifications@github.com>
发送时间: 2019年8月30日(星期五) 下午3:14
收件人: "Alivon/Panda-Learning"<Panda-Learning@noreply.github.com>;
抄送: "Neeao"<ywwg@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Alivon/Panda-Learning] 完美版自动学习(带验证码自动识别) (#469)



a=ice-ufrag:nEax
 a=ice-pwd:NtYnfaZ99P+axRJtx5bOSegy
 a=ice-options:trickle
 a=fingerprint:sha-256 71:36:1D:16:5A:6A:1D:3D:37:C0:A5:BD:86:A1:13:AB:2F:3A:80:7A:D2:61:7F:19:5E:00:4F:23:BC:43:B5:CC
 a=setup:actpass
 a=mid:0
 a=sendrecv
 a=msid:
 a=rtcp-mux
 a=rtpmap:119 google-data/90000
 a=ssrc:751334933 cname:ibjpJuBS9841Hl7n
 a=ssrc:751334933 msid:-
 a=ssrc:751334933 mslabel:-
 a=ssrc:751334933 label:
 
[0830/151012.800:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.
 开始获取验证码地址
 下载验证码! https://pin.aliyun.com/get_img?sessionid=k0143vyNSQo4c5GwrR7kN/WXSwQh6Xep67w5bvQz8uvQc=&identity=login.dingtalk.com&type=default
 Traceback (most recent call last):
 File "xxqg.py", line 180, in 
 File "xxqg.py", line 15, in user_flag
 File "pdlearn\dingding.py", line 25, in dd_login_status
 File "pdlearn\mydriver.py", line 116, in dd_login
 File "pdlearn\mydriver.py", line 152, in send_captcha_chaojiyin
 File "pdlearn\mydriver.py", line 180, in get_key_captcha
 ValueError: not enough values to unpack (expected 2, got 1)
 [11092] Failed to execute script xxqg
 
[兄弟这个怎么破
 
 
&mdash;

**Comment by zhouqie123** [comment]
> > 提示获取获取失败,,
> 
> 请检查是否配置了接口即/User/Key.ini文件

key,配置了，登陆成功就出现这个画面~
![1](https://user-images.githubusercontent.com/38326575/64002095-d9da9280-cb3b-11e9-87af-68a63704b506.png)

**Comment by newmean** [comment]
换个电脑试试？------------------ 原始邮件 ------------------
发件人: "zhouqie123"<notifications@github.com>
发送时间: 2019年8月30日(星期五) 下午3:36
收件人: "Alivon/Panda-Learning"<Panda-Learning@noreply.github.com>;
抄送: "Neeao"<ywwg@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Alivon/Panda-Learning] 完美版自动学习(带验证码自动识别) (#469)


  
提示获取获取失败,,
  
请检查是否配置了接口即/User/Key.ini文&#x4EF6;
  
key,配置了，登陆成功就出现这个画面~
 
 
&mdash;

**Comment by ggjj862** [comment]
谢谢楼主分享，另外楼主能发我一份源码吗？19041834@qq.com万分感谢！！

**Comment by newmean** [comment]
> 谢谢楼主分享，另外楼主能发我一份源码吗？[19041834@qq.com](mailto:19041834@qq.com)万分感谢！！

源码不就在这里吗?

**Comment by ggjj862** [comment]
我是说你的可以自动验证的这个源码。谢谢！！

**Comment by hjhjcj** [comment]
> 请先在[https://www.showapi.com/注册一个账号](https://www.showapi.com/%E6%B3%A8%E5%86%8C%E4%B8%80%E4%B8%AA%E8%B4%A6%E5%8F%B7)
> 然后在https://www.showapi.com/apiGateway/view?apiCode=184
> 花0.1元人民币购买100易豆,就有200次使用.(按照一个账号每天一次,你可以使用6个月以上.如果使用完了之后你可以重新注册账号然后再花0.1元购买)
> 然后在,个人中心-我的应用 里面查看APPID和密钥
> 并填写在User/Key.ini 文件里即可使用 第一个参数是APPID,第二个参数是密钥
> 
> 链接: https://pan.baidu.com/s/1dW_oLB2m4KXYdiwcCGVCwg
> 提取码: wyjj

链接挂了，请发个给我，谢谢。christinabruce7369@gmail.com

**Comment by newmean** [comment]
> > 请先在[https://www.showapi.com/注册一个账号](https://www.showapi.com/%E6%B3%A8%E5%86%8C%E4%B8%80%E4%B8%AA%E8%B4%A6%E5%8F%B7)
> > 然后在https://www.showapi.com/apiGateway/view?apiCode=184
> > 花0.1元人民币购买100易豆,就有200次使用.(按照一个账号每天一次,你可以使用6个月以上.如果使用完了之后你可以重新注册账号然后再花0.1元购买)
> > 然后在,个人中心-我的应用 里面查看APPID和密钥
> > 并填写在User/Key.ini 文件里即可使用 第一个参数是APPID,第二个参数是密钥
> > 链接: https://pan.baidu.com/s/1dW_oLB2m4KXYdiwcCGVCwg
> > 提取码: wyjj
> 
> 链接挂了，请发个给我，谢谢。[christinabruce7369@gmail.com](mailto:christinabruce7369@gmail.com)

链接: https://pan.baidu.com/s/11e-iHJ4Xam1AqPAAlA9dKA 提取码: 8wg8

**Comment by hjjcq2017** [comment]
楼主这个是多线程的 如何设置随机单线程，win10中如何设置用户标记名默认让系统自动自动运行（每次登录要手动输入用户标记名）

**Comment by clk0619** [comment]
> > > 请先在[https://www.showapi.com/注册一个账号](https://www.showapi.com/%E6%B3%A8%E5%86%8C%E4%B8%80%E4%B8%AA%E8%B4%A6%E5%8F%B7)
> > > 然后在https://www.showapi.com/apiGateway/view?apiCode=184
> > > 花0.1元人民币购买100易豆,就有200次使用.(按照一个账号每天一次,你可以使用6个月以上.如果使用完了之后你可以重新注册账号然后再花0.1元购买)
> > > 然后在,个人中心-我的应用 里面查看APPID和密钥
> > > 并填写在User/Key.ini 文件里即可使用 第一个参数是APPID,第二个参数是密钥
> > > 链接: https://pan.baidu.com/s/1dW_oLB2m4KXYdiwcCGVCwg
> > > 提取码: wyjj
> > 
> > 
> > 链接挂了，请发个给我，谢谢。[christinabruce7369@gmail.com](mailto:christinabruce7369@gmail.com)
> 
> 链接: https://pan.baidu.com/s/11e-iHJ4Xam1AqPAAlA9dKA 提取码: 8wg8

https://www.showapi.com/apiGateway/view?apiCode=184  这个链接已经404了，请问有办法吗？

**Comment by hjhjcj** [comment]
谢谢。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: clk0619 <notifications@github.com>
发送时间: Thursday, September 5, 2019 12:21:15 PM
收件人: Alivon/Panda-Learning <Panda-Learning@noreply.github.com>
抄送: hjhjcj <hjhjcj@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [Alivon/Panda-Learning] 完美版自动学习(带验证码自动识别) (#469)


请先在https://www.showapi.com/注册一个账号<https://www.showapi.com/%E6%B3%A8%E5%86%8C%E4%B8%80%E4%B8%AA%E8%B4%A6%E5%8F%B7>
然后在https://www.showapi.com/apiGateway/view?apiCode=184
花0.1元人民币购买100易豆,就有200次使用.(按照一个账号每天一次,你可以使用6个月以上.如果使用完了之后你可以重新注册账号然后再花0.1元购买)
然后在,个人中心-我的应用 里面查看APPID和密钥
并填写在User/Key.ini 文件里即可使用 第一个参数是APPID,第二个参数是密钥
链接: https://pan.baidu.com/s/1dW_oLB2m4KXYdiwcCGVCwg
提取码: wyjj

链接挂了，请发个给我，谢谢。christinabruce7369@gmail.com<mailto:christinabruce7369@gmail.com>

链接: https://pan.baidu.com/s/11e-iHJ4Xam1AqPAAlA9dKA 提取码: 8wg8

https://www.showapi.com/apiGateway/view?apiCode=184 这个链接已经404了，请问有办法吗？

―

**Comment by noway2014** [comment]
收费了？跟以前的程序有变化吗？

**Comment by massger** [comment]
![image](https://user-images.githubusercontent.com/27893737/64473143-37a05780-d198-11e9-8f15-527bc71a29f5.png)

**Comment by 1425698939** [comment]
感谢楼主大佬可以发我一份吗？链接失效404打不开。1425698939@qq.com
万分感谢楼主分享！

**Comment by SanfoLee** [comment]
> 请先在[https://www.showapi.com/注册一个账号](https://www.showapi.com/%E6%B3%A8%E5%86%8C%E4%B8%80%E4%B8%AA%E8%B4%A6%E5%8F%B7)
> 然后在https://www.showapi.com/apiGateway/view?apiCode=184
> 花0.1元人民币购买100易豆,就有200次使用.(按照一个账号每天一次,你可以使用6个月以上.如果使用完了之后你可以重新注册账号然后再花0.1元购买)
> 然后在,个人中心-我的应用 里面查看APPID和密钥
> 并填写在User/Key.ini 文件里即可使用 第一个参数是APPID,第二个参数是密钥
> 
> 链接: https://pan.baidu.com/s/1dW_oLB2m4KXYdiwcCGVCwg
> 提取码: wyjj

链接挂了，请发个给我，谢谢!   working_lsf@sina.com

**Comment by newmean** [comment]
> > ![image](https://user-images.githubusercontent.com/27893737/64473143-37a05780-d198-11e9-8f15-527bc71a29f5.png)登陆成功后出现这个界面
> 
> 我和你的情况一样

Bug 已修复,见最新下载地址.

**Comment by newmean** [comment]
> ![image](https://user-images.githubusercontent.com/27893737/64473143-37a05780-d198-11e9-8f15-527bc71a29f5.png)登陆成功后出现这个界面

Bug已修复,程序见最新下载地址.

**Comment by cherry845** [comment]
这个会被封号吗？原来的熊猫学习的作者呢？是你吗？原来的因为每天是固定的分数而封号的吗？现在这个能每天学习不一样的分数不？现在感觉有些害怕地说，求作者释疑，感谢万分！

**Comment by massger** [comment]
> > ![图片](https://user-images.githubusercontent.com/27893737/64473143-37a05780-d198-11e9-8f15-527bc71a29f5.png)登陆成功后出现这个界面
> 
> 错误已修复，程序见最新下载地址。

您好，新的下载地址怎么看不到呢

**Comment by newmean** [comment]
> > > ![图片](https://user-images.githubusercontent.com/27893737/64473143-37a05780-d198-11e9-8f15-527bc71a29f5.png)登陆成功后出现这个界面
> > 
> > 
> > 错误已修复，程序见最新下载地址。
> 
> 您好，新的下载地址怎么看不到呢

最新下载地址:https://pan.baidu.com/s/1fUXoE2MFuHByaxw-U4HUsA

**Comment by newmean** [comment]
会不会封号我不知道，原来作者我也不知道，我也不是原来的作者，每天固定25分，不能每天学习分数不一样。

**Comment by 188751671** [comment]
188751671@qq.com 同求

**Comment by massger** [comment]
![image](https://user-images.githubusercontent.com/27893737/65767643-0399d000-e161-11e9-8370-393581f9f56a.png)
报错了

**Comment by newmean** [comment]
> ![image](https://user-images.githubusercontent.com/27893737/65767643-0399d000-e161-11e9-8370-393581f9f56a.png)
> 报错了

请看Readme

**Comment by zhouqie123** [comment]
> 请先在[https://www.showapi.com/注册一个账号](https://www.showapi.com/%E6%B3%A8%E5%86%8C%E4%B8%80%E4%B8%AA%E8%B4%A6%E5%8F%B7)
> 然后在https://www.showapi.com/apiGateway/view?apiCode=184
> 花0.1元人民币购买100易豆,就有200次使用.(按照一个账号每天一次,你可以使用6个月以上.如果使用完了之后你可以重新注册账号然后再花0.1元购买)
> 然后在,个人中心-我的应用 里面查看APPID和密钥
> 并填写在User/Key.ini 文件里即可使用 第一个参数是APPID,第二个参数是密钥
> 
> **最新下载地址**:https://pan.baidu.com/s/1fUXoE2MFuHByaxw-U4HUsA

地址过期啦~

**Comment by zhouqie123** [comment]
地址过期了，能重新分享一个吗

**Comment by Crowl3y2019** [comment]
823649414@qq.com
求LZ分享一个！

**Comment by hahahahan** [comment]
525268749@qq.com  求LZ分享

**Comment by shajia1992** [comment]
大佬，求电报群邀请链接
