### ISSUE TITLE
mac启动不了，大神帮忙看看

### ISSUE THREAD

**Issue by gwd0715** [Alivon/Panda-Learning#473]
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "selenium/webdriver/common/service.py", line 76, in start
  File "subprocess.py", line 729, in __init__
  File "subprocess.py", line 1364, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

**Comment by shellalumni** [comment]
一模一样的问题

**Comment by PrettyXu** [comment]
现在还可以用么？ 验证码登录

**Comment by Hoontme** [comment]
请问有什么办法解决吗?

**Comment by Hoontme** [comment]
我已经解决了
运行的方式:mac os14源码运行;
找到source packages文件夹 下的 pdlearn 文件夹 中的pycache下的mydriver.py,在将函数get_cookies()整个替换为
def get_cookies(self):
        cookies = self.driver.get_cookies()
        for cookie in cookies:
            if 'expiry' in cookie:
                del cookie['expiry']
        return cookies
