### ISSUE TITLE
【BUG】请大神们解答

### ISSUE THREAD

**Issue by SoftPaper** [Alivon/Panda-Learning#480]
DevTools listening on ws://127.0.0.1:62693/devtools/browser/b739c819-3267-473e-9df1-4d26c1980710
[0903/162645.756:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0903/162645.756:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0903/162645.756:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0903/162645.756:ERROR:webrtc_sdp.cc(406)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[0903/162645.756:ERROR:rtc_peer_connection_handler.cc(2225)] Failed to create native session description. Type: offer SDP: v=0
o=- 757177553101799254 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS
m=application 9 UDP/TLS/RTP/SAVPF 119
c=IN IP4 0.0.0.0
b=AS:30
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:/Cxp
a=ice-pwd:wep5By5cD5UeTk5MtG002wFL
a=ice-options:trickle
a=fingerprint:sha-256 BD:7A:46:E3:94:69:80:2A:BA:04:00:33:FC:DE:BF:03:00:C2:09:FC:1C:11:5F:B4:8D:9A:DA:74:1A:C8:85:69
a=setup:actpass
a=mid:0
a=sendrecv
a=msid:
a=rtcp-mux
a=rtpmap:119 google-data/90000
a=ssrc:607747231 cname:1APuNY+VuSS+jxz9
a=ssrc:607747231 msid:-
a=ssrc:607747231 mslabel:-
a=ssrc:607747231 label:

[0903/162645.757:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn\dingding.py", line 24, in dd_login_status
  File "pdlearn\mydriver.py", line 95, in dd_login
IndexError: list index out of range
[13700] Failed to execute script pandalearning

**Comment by hcxss** [comment]
解决了吗

**Comment by SoftPaper** [comment]
> 解决了吗

没有。
