### ISSUE TITLE
不能文章阅读了

### ISSUE THREAD

**Issue by zxminglj** [Alivon/Panda-Learning#501]
每次阅读了但是阅读数量还是为0，研究下是什么问题。这样每天只能19分

**Comment by gundamgx** [comment]
Exception in thread 文章学习:
Traceback (most recent call last):
File "threading.py", line 926, in _bootstrap_inner
File "pdlearn\threads.py", line 23, in run
File "pandalearning.py", line 66, in article
IndexError: list index out of range
是这样的错误吧，重新登陆就好了

**Comment by zxminglj** [comment]
> Exception in thread 文章学习:
> Traceback (most recent call last):
> File "threading.py", line 926, in _bootstrap_inner
> File "pdlearn\threads.py", line 23, in run
> File "pandalearning.py", line 66, in article
> IndexError: list index out of range
> 是这样的错误吧，重新登陆就好了

是的，应该是代码没有完善，最近很频繁出现这个问题。
