### ISSUE TITLE
Linux版的问题

### ISSUE THREAD

**Issue by tasagapro** [Alivon/Panda-Learning#51]
Linux版本有问题。错误如下：
tasagapro@tasagapro-ubuntu:~$ cd pandalearning-linux/
tasagapro@tasagapro-ubuntu:~/pandalearning-linux$ ./pandalearn 
熊猫学习下载地址为 https://github.com/Alivon/Panda-Learning
该链接有详细使用说明，转发请发此链接给真正需要使用的人，而不是使此款软体消失的人
请输入用户名: tasagapro
Traceback (most recent call last):
  File "selenium/webdriver/common/service.py", line 76, in start
  File "subprocess.py", line 947, in __init__
  File "subprocess.py", line 1551, in _execute_child
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearn.py", line 217, in <module>
  File "selenium/webdriver/chrome/webdriver.py", line 73, in __init__
  File "selenium/webdriver/common/service.py", line 88, in start
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

[6773] Failed to execute script pandalearn
系统版本为：Ubuntu 18.04.2

**Comment by Alivon** [comment]
chromedriver 地址问题 请放在主程序相同文件路径下

**Comment by zyftank** [comment]
> chromedriver 地址问题 请放在主程序相同文件路径下

linux版是不是要桌面版的？

**Comment by zyftank** [comment]
> chromedriver 地址问题 请放在主程序相同文件路径下
ubutnu 服务器版，安装了selenium和chromedriver 后运行出现下面错误，是什么情况？
TypeError: urlopen() got multiple values for keyword argument 'body'

**Comment by xenonum** [comment]
Traceback (most recent call last):
  File "pandalearning.py", line 176, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn/dingding.py", line 23, in dd_login_status
  File "pdlearn/mydriver.py", line 22, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 81, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 157, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 252, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.15.0-47-generic x86_64)

**Comment by xenonum** [comment]
how to fix it?

**Comment by zyftank** [comment]
给浏览器加个参数--no-sandbox试试

**Comment by xenonum** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearning.py", line 176, in <module>
  File "pandalearning.py", line 21, in user_flag
  File "pdlearn/dingding.py", line 23, in dd_login_status
  File "pdlearn/mydriver.py", line 22, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 73, in __init__
  File "selenium/webdriver/common/service.py", line 88, in start
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by xenonum** [comment]
> 给浏览器加个参数--no-sandbox试试

linux下怎么加？加在/usr/bin/google-chrome 里？

**Comment by zyftank** [comment]
这个是在源代码里加的
