### ISSUE TITLE
PI2B+ Raspberry 系统无法运行

### ISSUE THREAD

**Issue by EmonLieu** [Alivon/Panda-Learning#98]
系统信息如下，最新版不只是否是编译环境不同导致，大佬是否愿意开源自行打包 ，或者编译一下ARM下的二进制包？ 文件权限没有问题。
![QQ图片20190327170826](https://user-images.githubusercontent.com/26017160/55063532-20225600-50b3-11e9-8199-1b47891f7c2f.png)

**Comment by asdqwe111** [comment]
楼主，原来那个源码，我自行打包了以后，发现执行的时候，提示有错误。。。
你自行打包的时候，可不可以给点提示，未实名我打包的时候有问题，是只用一个pandalearning.py打包的还是还有其他东西？

**Comment by Alivon** [comment]
源码以更新 我手中没有开发版或树莓派测试，如果打包好了欢迎也希望提交上来

**Comment by EmonLieu** [comment]
> 源码以更新 我手中没有开发版或树莓派测试，如果打包好了欢迎也希望提交上来

刚打包好。。就更新了 诶。。。

**Comment by Alivon** [comment]
针对今天强国更新后，pandalearning已紧急修复！！！ 请至github重新下载

EmonLieu <notifications@github.com> 于2019年3月28日周四 下午1:01写道：

**Comment by EmonLieu** [comment]
@asdqwe111 pyinstaller会自动依赖，请问具体事什么错误，我自己打包的目前运行可以，但是跟驱动的匹配还有点问题，研究出来了我会提交上来，树莓派的编译架构是armhf的，驱动什么的都要找匹配的

**Comment by mr-zl** [comment]
> @ asdqwe111 pyinstaller会自动依赖，请问具体事什么错误，我自己打包的目前运行可以，但是跟驱动的匹配还有点问题，研究出来了我会提交上来，树莓派的编译架构是armhf的，驱动什么的都要找匹配的

Traceback (most recent call last):
  File "pandalearning.py", line 4, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "pdlearn/version.py", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "requests/__init__.py", line 63, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "requests/utils.py", line 24, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "requests/_internal_utils.py", line 11, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "requests/compat.py", line 11, in <module>
ImportError: cannot import name 'chardet'
[10929] Failed to execute script pandalearning


打包后运行出现这个错误，源码可以执行

**Comment by EmonLieu** [comment]
> > @ asdqwe111 pyinstaller会自动依赖，请问具体事什么错误，我自己打包的目前运行可以，但是跟驱动的匹配还有点问题，研究出来了我会提交上来，树莓派的编译架构是armhf的，驱动什么的都要找匹配的
> 
> Traceback (most recent call last):
> File "pandalearning.py", line 4, in 
> File "/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
> exec(bytecode, module.**dict**)
> File "pdlearn/version.py", line 1, in 
> File "/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
> exec(bytecode, module.**dict**)
> File "requests/**init**.py", line 63, in 
> File "/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
> exec(bytecode, module.**dict**)
> File "requests/utils.py", line 24, in 
> File "/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
> exec(bytecode, module.**dict**)
> File "requests/_internal_utils.py", line 11, in 
> File "/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
> exec(bytecode, module.**dict**)
> File "requests/compat.py", line 11, in 
> ImportError: cannot import name 'chardet'
> [10929] Failed to execute script pandalearning
> 
> 打包后运行出现这个错误，源码可以执行

你可以尝试一下重装requests

**Comment by mr-zl** [comment]
> > > @ asdqwe111 pyinstaller会自动依赖，请问具体事什么错误，我自己打包的目前运行可以，但是跟驱动的匹配还有点问题，研究出来了我会提交上来，树莓派的编译架构是armhf的，驱动什么的都要找匹配的
> > 
> > 
> > 回溯（最近一次调用最后一次）：
> > 文件“pandalearning.py”，第4行，在
> > 文件“/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/ PyInstaller /装载器/ pyimod03_importers.py “线路627，在exec_module 
> > EXEC（字节码，模块。**字典**）
> > 文件”pdlearn / version.py“，第1行，在
> > 文件” /usr/local/lib/python3.5/dist-包/ PyInstaller-3.5.dev0 + b54a15d72e-py3.5.egg / PyInstaller /装载器/ pyimod03_importers.py”，线路627，在exec_module 
> > EXEC（字节码，模块。**字典**）
> > 文件“请求/ **初始化** py”为63行，在
> > 文件“/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader/pyimod03_importers.py”，第627行，在exec_module 
> > exec中（字节码，模块） 。**字典**）
> > 文件“请求/ utils.py”，第24行，在
> > 文件“/usr/local/lib/python3.5/dist-packages/PyInstaller-3.5.dev0+b54a15d72e-py3.5.egg/PyInstaller/loader /pyimod03_importers.py “线路627，在exec_module 
> > EXEC（字节码，模块。**字典**）
> > 文件”请求/ _internal_utils.py“，第11行，在
> > 文件” /usr/local/lib/python3.5/dist-packages/PyInstaller -3.5.dev0 + b54a15d72e-py3.5.egg / PyInstaller /装载器/ pyimod03_importers.py”，线路627，在exec_module 
> > EXEC（字节码，模块。**字典**）
> > 在
> > ImportError中的文件“requests / compat.py”，第11行：无法导入名称'chardet' 
> > [10929]无法执行脚本pandalearning
> > 打包后运行出现这个错误，源码可以执行
> 
> 你可以尝试一下重装请求

刚刚重装，竟然重装失败
